/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

//#line  214 "./include/ppu/stddef.h"
typedef unsigned long size_t;
//#line  31 "/usr/include/bits/types.h"
typedef unsigned char __u_char;
//#line  32 "/usr/include/bits/types.h"
typedef unsigned short __u_short;
//#line  33 "/usr/include/bits/types.h"
typedef unsigned int __u_int;
//#line  34 "/usr/include/bits/types.h"
typedef unsigned long __u_long;
//#line  37 "/usr/include/bits/types.h"
typedef signed char __int8_t;
//#line  38 "/usr/include/bits/types.h"
typedef unsigned char __uint8_t;
//#line  39 "/usr/include/bits/types.h"
typedef short __int16_t;
//#line  40 "/usr/include/bits/types.h"
typedef unsigned short __uint16_t;
//#line  41 "/usr/include/bits/types.h"
typedef int __int32_t;
//#line  42 "/usr/include/bits/types.h"
typedef unsigned int __uint32_t;
//#line  44 "/usr/include/bits/types.h"
typedef long __int64_t;
//#line  45 "/usr/include/bits/types.h"
typedef unsigned long __uint64_t;
//#line  53 "/usr/include/bits/types.h"
typedef long __quad_t;
//#line  54 "/usr/include/bits/types.h"
typedef unsigned long __u_quad_t;
//#line  134 "/usr/include/bits/types.h"
typedef unsigned long __dev_t;
//#line  135 "/usr/include/bits/types.h"
typedef unsigned int __uid_t;
//#line  136 "/usr/include/bits/types.h"
typedef unsigned int __gid_t;
//#line  137 "/usr/include/bits/types.h"
typedef unsigned long __ino_t;
//#line  138 "/usr/include/bits/types.h"
typedef unsigned long __ino64_t;
//#line  139 "/usr/include/bits/types.h"
typedef unsigned int __mode_t;
//#line  140 "/usr/include/bits/types.h"
typedef unsigned long __nlink_t;
//#line  141 "/usr/include/bits/types.h"
typedef long __off_t;
//#line  142 "/usr/include/bits/types.h"
typedef long __off64_t;
//#line  143 "/usr/include/bits/types.h"
typedef int __pid_t;
//#line  144 "/usr/include/bits/types.h"
struct __anonstruct___fsid_t_1 {
   int __val[2] ;
};
//#line  144 "/usr/include/bits/types.h"
typedef struct __anonstruct___fsid_t_1 __fsid_t;
//#line  145 "/usr/include/bits/types.h"
typedef long __clock_t;
//#line  146 "/usr/include/bits/types.h"
typedef unsigned long __rlim_t;
//#line  147 "/usr/include/bits/types.h"
typedef unsigned long __rlim64_t;
//#line  148 "/usr/include/bits/types.h"
typedef unsigned int __id_t;
//#line  149 "/usr/include/bits/types.h"
typedef long __time_t;
//#line  150 "/usr/include/bits/types.h"
typedef unsigned int __useconds_t;
//#line  151 "/usr/include/bits/types.h"
typedef long __suseconds_t;
//#line  153 "/usr/include/bits/types.h"
typedef int __daddr_t;
//#line  154 "/usr/include/bits/types.h"
typedef long __swblk_t;
//#line  155 "/usr/include/bits/types.h"
typedef int __key_t;
//#line  158 "/usr/include/bits/types.h"
typedef int __clockid_t;
//#line  161 "/usr/include/bits/types.h"
typedef void *__timer_t;
//#line  164 "/usr/include/bits/types.h"
typedef long __blksize_t;
//#line  169 "/usr/include/bits/types.h"
typedef long __blkcnt_t;
//#line  170 "/usr/include/bits/types.h"
typedef long __blkcnt64_t;
//#line  173 "/usr/include/bits/types.h"
typedef unsigned long __fsblkcnt_t;
//#line  174 "/usr/include/bits/types.h"
typedef unsigned long __fsblkcnt64_t;
//#line  177 "/usr/include/bits/types.h"
typedef unsigned long __fsfilcnt_t;
//#line  178 "/usr/include/bits/types.h"
typedef unsigned long __fsfilcnt64_t;
//#line  180 "/usr/include/bits/types.h"
typedef long __ssize_t;
//#line  184 "/usr/include/bits/types.h"
typedef __off64_t __loff_t;
//#line  185 "/usr/include/bits/types.h"
typedef __quad_t *__qaddr_t;
//#line  186 "/usr/include/bits/types.h"
typedef char *__caddr_t;
//#line  189 "/usr/include/bits/types.h"
typedef long __intptr_t;
//#line  192 "/usr/include/bits/types.h"
typedef unsigned int __socklen_t;
//#line  45 "/usr/include/stdio.h"
struct _IO_FILE;
//#line  49 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;
//#line  65 "/usr/include/stdio.h"
typedef struct _IO_FILE __FILE;
//#line  83 "/usr/include/wchar.h"
union __anonunion___value_3 {
   unsigned int __wch ;
   char __wchb[4] ;
};
//#line  83 "/usr/include/wchar.h"
struct __anonstruct___mbstate_t_2 {
   int __count ;
   union __anonunion___value_3 __value ;
};
//#line  83 "/usr/include/wchar.h"
typedef struct __anonstruct___mbstate_t_2 __mbstate_t;
//#line  22 "/usr/include/_G_config.h"
struct __anonstruct__G_fpos_t_4 {
   __off_t __pos ;
   __mbstate_t __state ;
};
//#line  22 "/usr/include/_G_config.h"
typedef struct __anonstruct__G_fpos_t_4 _G_fpos_t;
//#line  27 "/usr/include/_G_config.h"
struct __anonstruct__G_fpos64_t_5 {
   __off64_t __pos ;
   __mbstate_t __state ;
};
//#line  27 "/usr/include/_G_config.h"
typedef struct __anonstruct__G_fpos64_t_5 _G_fpos64_t;
//#line  53 "/usr/include/_G_config.h"
typedef short _G_int16_t;
//#line  54 "/usr/include/_G_config.h"
typedef int _G_int32_t;
//#line  55 "/usr/include/_G_config.h"
typedef unsigned short _G_uint16_t;
//#line  56 "/usr/include/_G_config.h"
typedef unsigned int _G_uint32_t;
//#line  44 "./include/ppu/stdarg.h"
typedef __builtin_va_list __gnuc_va_list;
//#line  170 "/usr/include/libio.h"
struct _IO_jump_t;
//#line  180 "/usr/include/libio.h"
typedef void _IO_lock_t;
//#line  186 "/usr/include/libio.h"
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
//#line  206
enum __codecvt_result {
    __codecvt_ok = 0,
    __codecvt_partial = 1,
    __codecvt_error = 2,
    __codecvt_noconv = 3
} ;
//#line  271 "/usr/include/libio.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
//#line  341 "/usr/include/libio.h"
typedef struct _IO_FILE _IO_FILE;
//#line  344
struct _IO_FILE_plus;
//#line  364 "/usr/include/libio.h"
typedef __ssize_t __io_read_fn(void *__cookie , char *__buf , size_t __nbytes );
//#line  372 "/usr/include/libio.h"
typedef __ssize_t __io_write_fn(void *__cookie , char const   *__buf , size_t __n );
//#line  381 "/usr/include/libio.h"
typedef int __io_seek_fn(void *__cookie , __off64_t *__pos , int __w );
//#line  384 "/usr/include/libio.h"
typedef int __io_close_fn(void *__cookie );
//#line  91 "/usr/include/stdio.h"
typedef _G_fpos_t fpos_t;
//#line  37 "/usr/include/stdint.h"
typedef signed char int8_t;
//#line  38 "/usr/include/stdint.h"
typedef short int16_t;
//#line  39 "/usr/include/stdint.h"
typedef int int32_t;
//#line  41 "/usr/include/stdint.h"
typedef long int64_t;
//#line  49 "/usr/include/stdint.h"
typedef unsigned char uint8_t;
//#line  50 "/usr/include/stdint.h"
typedef unsigned short uint16_t;
//#line  52 "/usr/include/stdint.h"
typedef unsigned int uint32_t;
//#line  56 "/usr/include/stdint.h"
typedef unsigned long uint64_t;
//#line  66 "/usr/include/stdint.h"
typedef signed char int_least8_t;
//#line  67 "/usr/include/stdint.h"
typedef short int_least16_t;
//#line  68 "/usr/include/stdint.h"
typedef int int_least32_t;
//#line  70 "/usr/include/stdint.h"
typedef long int_least64_t;
//#line  77 "/usr/include/stdint.h"
typedef unsigned char uint_least8_t;
//#line  78 "/usr/include/stdint.h"
typedef unsigned short uint_least16_t;
//#line  79 "/usr/include/stdint.h"
typedef unsigned int uint_least32_t;
//#line  81 "/usr/include/stdint.h"
typedef unsigned long uint_least64_t;
//#line  91 "/usr/include/stdint.h"
typedef signed char int_fast8_t;
//#line  93 "/usr/include/stdint.h"
typedef long int_fast16_t;
//#line  94 "/usr/include/stdint.h"
typedef long int_fast32_t;
//#line  95 "/usr/include/stdint.h"
typedef long int_fast64_t;
//#line  104 "/usr/include/stdint.h"
typedef unsigned char uint_fast8_t;
//#line  106 "/usr/include/stdint.h"
typedef unsigned long uint_fast16_t;
//#line  107 "/usr/include/stdint.h"
typedef unsigned long uint_fast32_t;
//#line  108 "/usr/include/stdint.h"
typedef unsigned long uint_fast64_t;
//#line  120 "/usr/include/stdint.h"
typedef long intptr_t;
//#line  123 "/usr/include/stdint.h"
typedef unsigned long uintptr_t;
//#line  135 "/usr/include/stdint.h"
typedef long intmax_t;
//#line  136 "/usr/include/stdint.h"
typedef unsigned long uintmax_t;
//#line  39 "include/tpc_common.h"
enum compl_status {
    WAITING = 0,
    COMPLETED = 1
} ;
//#line  41
enum entry_status {
    INACTIVE = 0,
    ACTIVE = 1
} ;
//#line  45 "include/tpc_common.h"
struct tpc_arg_element {
   uint32_t flag ;
   uint32_t size ;
   uint32_t eal ;
   uint32_t stride ;
} __attribute__((__aligned__(16))) ;
//#line  54 "include/tpc_common.h"
struct queue_entry {
   struct tpc_arg_element arguments[18U] ;
   uint32_t ea_upper ;
   uint8_t funcid ;
   uint8_t total_arguments ;
   enum entry_status active ;
} __attribute__((__aligned__(16))) ;
//#line  64 "include/tpc_common.h"
typedef struct queue_entry queue_entry_t;
//#line  66 "include/tpc_common.h"
struct completions_status_t {
   enum compl_status status ;
   int return_value ;
} __attribute__((__aligned__(128))) ;
//#line  75 "include/tpc_common.h"
struct tpc_ppe_statistics_t {
   uint64_t stalled_ticks ;
   uint64_t issue_ticks ;
   uint64_t wait_ticks ;
   uint32_t stat_total_blocks ;
   uint64_t stat_tpc_per_spe[16U] ;
   uint64_t bytes_per_spe[16U] ;
} __attribute__((__aligned__(128))) ;
//#line  88 "include/tpc_common.h"
struct tpc_spe_statistics_t {
   uint64_t idle_ticks ;
   uint64_t lib_ticks ;
   uint64_t argsin_ticks ;
   uint64_t argsout_ticks ;
   uint64_t task_ticks ;
   uint64_t final_ticks ;
   uint64_t prefetch_count ;
   uint64_t fetch_count ;
   unsigned int __attribute__((__spu_vector__))  idle_flag ;
} __attribute__((__aligned__(128))) ;
//#line  49 "./include/spu/spu_internals.h"
typedef signed char __attribute__((__spu_vector__))  qword;
//#line  49 "./include/spu/spu_mfcio.h"
struct mfc_list_element {
   uint64_t notify : 1 ;
   uint64_t reserved : 16 ;
   uint64_t size : 15 ;
   uint64_t eal : 32 ;
};
//#line  49 "./include/spu/spu_mfcio.h"
typedef struct mfc_list_element mfc_list_element_t;
//#line  11 "include/tpc_spe.h"
enum task_state {
    UNFETCHED = 0,
    FETCHING = 1,
    FETCHED = 2,
    EXECUTED = 3,
    WRITINGBACK = 4,
    WRITENBACK = 5
} ;
//#line  21 "include/tpc_spe.h"
struct tpc_spe_task_state {
   void *ls_addr ;
   enum task_state state ;
   int dmatag ;
   mfc_list_element_t *dmalist ;
   int isPrepared ;
   unsigned int mfclist_offset ;
   unsigned int outListElements ;
   unsigned int totalListElements ;
   unsigned int totalBytes ;
} __attribute__((__aligned__(16))) ;
//#line  33 "include/tpc_spe.h"
typedef struct tpc_spe_task_state tpc_spe_task_state_t;
/* compiler builtin: 
   void __builtin_varargs_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   int __builtin_strcmp(char const   * , char const   * ) ;  */
/* compiler builtin: 
   void *__builtin___memmove_chk(void * , void const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   char *__builtin_strpbrk(char const   * , char const   * ) ;  */
/* compiler builtin: 
   void *__builtin_memcpy(void * , void const   * , unsigned long  ) ;  */
/* compiler builtin: 
   double __builtin_exp(double  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_and_and_fetch(...) ;  */
/* compiler builtin: 
   long double __builtin_nanl(char const   * ) ;  */
/* compiler builtin: 
   double __builtin_cos(double  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_nand_and_fetch(...) ;  */
/* compiler builtin: 
   char *__builtin_strchr(char * , int  ) ;  */
/* compiler builtin: 
   float __builtin_atan2f(float  , float  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_nand(...) ;  */
/* compiler builtin: 
   void *__builtin___memcpy_chk(void * , void const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   double __builtin_asin(double  ) ;  */
/* compiler builtin: 
   int __builtin_ctz(unsigned int  ) ;  */
/* compiler builtin: 
   char *__builtin_stpcpy(char * , char const   * ) ;  */
/* compiler builtin: 
   void __sync_synchronize(...) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_unpckhps(float __attribute__((____vector_size____(16)))   ,
                                                                           float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   double __builtin_nans(char const   * ) ;  */
/* compiler builtin: 
   long double __builtin_atan2l(long double  , long double  ) ;  */
/* compiler builtin: 
   float __builtin_logf(float  ) ;  */
/* compiler builtin: 
   int __builtin___fprintf_chk(void * , int  , char const   *  , ...) ;  */
/* compiler builtin: 
   int __builtin___vsprintf_chk(char * , int  , unsigned long  , char const   * ,
                                __builtin_va_list  ) ;  */
/* compiler builtin: 
   char *__builtin___strncpy_chk(char * , char const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_subps(float __attribute__((____vector_size____(16)))   ,
                                                                        float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   float __builtin_log10f(float  ) ;  */
/* compiler builtin: 
   double __builtin_atan(double  ) ;  */
/* compiler builtin: 
   void *__builtin_alloca(unsigned long  ) ;  */
/* compiler builtin: 
   void __builtin_va_end(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_lock_test_and_set(...) ;  */
/* compiler builtin: 
   int __builtin_strncmp(char const   * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   double __builtin_sin(double  ) ;  */
/* compiler builtin: 
   long double __builtin_logl(long double  ) ;  */
/* compiler builtin: 
   float __builtin_coshf(float  ) ;  */
/* compiler builtin: 
   void *__builtin___mempcpy_chk(void * , void const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   char *__builtin___strcat_chk(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   float __builtin_nansf(char const   * ) ;  */
/* compiler builtin: 
   void *__builtin_memset(void * , int  , int  ) ;  */
/* compiler builtin: 
   void __builtin_va_copy(__builtin_va_list  , __builtin_va_list  ) ;  */
/* compiler builtin: 
   float __builtin_sinhf(float  ) ;  */
/* compiler builtin: 
   long double __builtin_log10l(long double  ) ;  */
/* compiler builtin: 
   long double __builtin_coshl(long double  ) ;  */
/* compiler builtin: 
   unsigned long __builtin_strlen(char const   * ) ;  */
/* compiler builtin: 
   int __builtin_ffs(unsigned int  ) ;  */
/* compiler builtin: 
   float __builtin_asinf(float  ) ;  */
/* compiler builtin: 
   long double __builtin_nansl(char const   * ) ;  */
/* compiler builtin: 
   double __builtin_frexp(double  , int * ) ;  */
/* compiler builtin: 
   double __builtin_tan(double  ) ;  */
/* compiler builtin: 
   long double __builtin_sinhl(long double  ) ;  */
/* compiler builtin: 
   float __builtin_frexpf(float  , int * ) ;  */
/* compiler builtin: 
   long double __builtin_asinl(long double  ) ;  */
/* compiler builtin: 
   void *__builtin_frame_address(unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_floor(double  ) ;  */
/* compiler builtin: 
   float __builtin_tanhf(float  ) ;  */
/* compiler builtin: 
   int __builtin_parityl(unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin_clzl(unsigned long  ) ;  */
/* compiler builtin: 
   double __builtin_powi(double  , int  ) ;  */
/* compiler builtin: 
   long double __builtin_frexpl(long double  , int * ) ;  */
/* compiler builtin: 
   float __builtin_atanf(float  ) ;  */
/* compiler builtin: 
   float __builtin_huge_valf(void) ;  */
/* compiler builtin: 
   float __builtin_sqrtf(float  ) ;  */
/* compiler builtin: 
   float __builtin_fmodf(float  ) ;  */
/* compiler builtin: 
   unsigned long __builtin_object_size(void * , int  ) ;  */
/* compiler builtin: 
   void __builtin_va_arg(__builtin_va_list  , unsigned long  , void * ) ;  */
/* compiler builtin: 
   void __builtin_stdarg_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_mulps(float __attribute__((____vector_size____(16)))   ,
                                                                        float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   long double __builtin_tanhl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_nan(char const   * ) ;  */
/* compiler builtin: 
   void __builtin_return(void const   * ) ;  */
/* compiler builtin: 
   long double __builtin_atanl(long double  ) ;  */
/* compiler builtin: 
   _Bool __sync_bool_compare_and_swap(...) ;  */
/* compiler builtin: 
   long double __builtin_huge_vall(void) ;  */
/* compiler builtin: 
   float __builtin_inff(void) ;  */
/* compiler builtin: 
   long double __builtin_sqrtl(long double  ) ;  */
/* compiler builtin: 
   long double __builtin_fmodl(long double  ) ;  */
/* compiler builtin: 
   int __builtin___printf_chk(int  , char const   *  , ...) ;  */
/* compiler builtin: 
   float __builtin_floorf(float  ) ;  */
/* compiler builtin: 
   float __builtin_fabsf(float  ) ;  */
/* compiler builtin: 
   int __builtin_popcountll(unsigned long long  ) ;  */
/* compiler builtin: 
   int __builtin___sprintf_chk(char * , int  , unsigned long  , char const   *  , ...) ;  */
/* compiler builtin: 
   int __builtin___vprintf_chk(int  , char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_maxps(float __attribute__((____vector_size____(16)))   ,
                                                                        float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   int __builtin___snprintf_chk(char * , unsigned long  , int  , unsigned long  ,
                                char const   *  , ...) ;  */
/* compiler builtin: 
   long double __builtin_infl(void) ;  */
/* compiler builtin: 
   void *__builtin_mempcpy(void * , void const   * , unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_floorl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_ctzl(unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_fabsl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_clz(unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_fabs(double  ) ;  */
/* compiler builtin: 
   int __builtin_popcount(unsigned int  ) ;  */
/* compiler builtin: 
   void __builtin_bcopy(void const   * , void * , unsigned long  ) ;  */
/* compiler builtin: 
   double __builtin_ceil(double  ) ;  */
/* compiler builtin: 
   double __builtin_ldexp(double  , int  ) ;  */
/* compiler builtin: 
   float __builtin_sinf(float  ) ;  */
/* compiler builtin: 
   float __builtin_acosf(float  ) ;  */
/* compiler builtin: 
   int __builtin___vsnprintf_chk(char * , unsigned long  , int  , unsigned long  ,
                                 char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   double __builtin_sinh(double  ) ;  */
/* compiler builtin: 
   int __builtin_ffsll(unsigned long long  ) ;  */
/* compiler builtin: 
   char *__builtin___strcpy_chk(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   double __builtin_inf(void) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_or_and_fetch(...) ;  */
/* compiler builtin: 
   void __builtin_prefetch(void const   *  , ...) ;  */
/* compiler builtin: 
   long double __builtin_sinl(long double  ) ;  */
/* compiler builtin: 
   long double __builtin_acosl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_sqrt(double  ) ;  */
/* compiler builtin: 
   double __builtin_fmod(double  ) ;  */
/* compiler builtin: 
   char *__builtin_strcpy(char * , char const   * ) ;  */
/* compiler builtin: 
   float __builtin_ceilf(float  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_xor_and_fetch(...) ;  */
/* compiler builtin: 
   void *__builtin_return_address(unsigned int  ) ;  */
/* compiler builtin: 
   char *__builtin___stpcpy_chk(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_sub_and_fetch(...) ;  */
/* compiler builtin: 
   float __builtin_tanf(float  ) ;  */
/* compiler builtin: 
   int __builtin_parityll(unsigned long long  ) ;  */
/* compiler builtin: 
   float __builtin_ldexpf(float  , int  ) ;  */
/* compiler builtin: 
   int __builtin_types_compatible_p(unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   double __builtin_log10(double  ) ;  */
/* compiler builtin: 
   float __builtin_expf(float  ) ;  */
/* compiler builtin: 
   int __builtin_clzll(unsigned long long  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_unpcklps(float __attribute__((____vector_size____(16)))   ,
                                                                           float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   double __builtin_tanh(double  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_add_and_fetch(...) ;  */
/* compiler builtin: 
   int __builtin_constant_p(int  ) ;  */
/* compiler builtin: 
   long double __builtin_ceill(long double  ) ;  */
/* compiler builtin: 
   int __builtin_va_arg_pack_len(void) ;  */
/* compiler builtin: 
   void *__builtin_apply(void (*)() , void * , unsigned long  ) ;  */
/* compiler builtin: 
   void __sync_lock_release(...) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_sub(...) ;  */
/* compiler builtin: 
   long double __builtin_tanl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_log(double  ) ;  */
/* compiler builtin: 
   long double __builtin_ldexpl(long double  , int  ) ;  */
/* compiler builtin: 
   int __builtin_popcountl(unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_expl(long double  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_val_compare_and_swap(...) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_or(...) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_and(...) ;  */
/* compiler builtin: 
   void *__builtin___memset_chk(void * , int  , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   char *__builtin___strncat_chk(char * , char const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   double __builtin_huge_val(void) ;  */
/* compiler builtin: 
   __builtin_va_list __builtin_next_arg(void) ;  */
/* compiler builtin: 
   void *__builtin_apply_args(void) ;  */
/* compiler builtin: 
   float __builtin_powif(float  , int  ) ;  */
/* compiler builtin: 
   int __builtin___vfprintf_chk(void * , int  , char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   float __builtin_modff(float  , float * ) ;  */
/* compiler builtin: 
   double __builtin_atan2(double  , double  ) ;  */
/* compiler builtin: 
   char *__builtin_strncpy(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_add(...) ;  */
/* compiler builtin: 
   long double __builtin_powil(long double  , int  ) ;  */
/* compiler builtin: 
   float __builtin_cosf(float  ) ;  */
/* compiler builtin: 
   void __builtin_bzero(void * , unsigned long  ) ;  */
/* compiler builtin: 
   unsigned long __builtin_strspn(char const   * , char const   * ) ;  */
/* compiler builtin: 
   long double __builtin_modfl(long double  , long double * ) ;  */
/* compiler builtin: 
   int __builtin_parity(unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_cosh(double  ) ;  */
/* compiler builtin: 
   char *__builtin_strncat(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   long __builtin_expect(long  , long  ) ;  */
/* compiler builtin: 
   double __builtin_acos(double  ) ;  */
/* compiler builtin: 
   int __builtin_va_arg_pack(void) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_addps(float __attribute__((____vector_size____(16)))   ,
                                                                        float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   long double __builtin_cosl(long double  ) ;  */
/* compiler builtin: 
   void __builtin_va_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   int __builtin_ctzll(unsigned long long  ) ;  */
/* compiler builtin: 
   unsigned long __builtin_strcspn(char const   * , char const   * ) ;  */
/* compiler builtin: 
   int __builtin_ffsl(unsigned long  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_xor(...) ;  */
/* compiler builtin: 
   float __builtin_nanf(char const   * ) ;  */
//#line  36 "tpc_s2s.h"
extern signed char __attribute__((__spu_vector__))  __builtin_si_frest(signed char __attribute__((__spu_vector__))   ) ;
//#line  37
extern signed char __attribute__((__spu_vector__))  __builtin_si_fi(signed char __attribute__((__spu_vector__))   ,
                                                                    signed char __attribute__((__spu_vector__))   ) ;
//#line  38
extern signed char __attribute__((__spu_vector__))  __builtin_si_frsqest(signed char __attribute__((__spu_vector__))   ) ;
//#line  39
extern void __builtin_si_wrch(int  , signed char __attribute__((__spu_vector__))   ) ;
//#line  40
extern signed char __attribute__((__spu_vector__))  __builtin_si_rdch(int  ) ;
//#line  41
extern signed char __attribute__((__spu_vector__))  __builtin_si_from_ptr(void * ) ;
//#line  42
extern signed char __attribute__((__spu_vector__))  __builtin_si_from_uint(unsigned int  ) ;
//#line  43
extern unsigned int __builtin_si_to_uint(signed char __attribute__((__spu_vector__))   ) ;
//#line  346 "/usr/include/libio.h"
extern struct _IO_FILE_plus _IO_2_1_stdin_ ;
//#line  347
extern struct _IO_FILE_plus _IO_2_1_stdout_ ;
//#line  348
extern struct _IO_FILE_plus _IO_2_1_stderr_ ;
//#line  416
extern int __underflow(_IO_FILE * ) ;
//#line  417
extern int __uflow(_IO_FILE * ) ;
//#line  418
extern int __overflow(_IO_FILE * , int  ) ;
//#line  460
extern int _IO_getc(_IO_FILE *__fp ) ;
//#line  461
extern int _IO_putc(int __c , _IO_FILE *__fp ) ;
//#line  462
extern  __attribute__((__nothrow__)) int _IO_feof(_IO_FILE *__fp ) ;
//#line  463
extern  __attribute__((__nothrow__)) int _IO_ferror(_IO_FILE *__fp ) ;
//#line  465
extern int _IO_peekc_locked(_IO_FILE *__fp ) ;
//#line  471
extern  __attribute__((__nothrow__)) void _IO_flockfile(_IO_FILE * ) ;
//#line  472
extern  __attribute__((__nothrow__)) void _IO_funlockfile(_IO_FILE * ) ;
//#line  473
extern  __attribute__((__nothrow__)) int _IO_ftrylockfile(_IO_FILE * ) ;
//#line  490
extern int _IO_vfscanf(_IO_FILE * __restrict   , char const   * __restrict   , __gnuc_va_list  ,
                       int * __restrict   ) ;
//#line  492
extern int _IO_vfprintf(_IO_FILE * __restrict   , char const   * __restrict   , __gnuc_va_list  ) ;
//#line  494
extern __ssize_t _IO_padn(_IO_FILE * , int  , __ssize_t  ) ;
//#line  495
extern size_t _IO_sgetn(_IO_FILE * , void * , size_t  ) ;
//#line  497
extern __off64_t _IO_seekoff(_IO_FILE * , __off64_t  , int  , int  ) ;
//#line  498
extern __off64_t _IO_seekpos(_IO_FILE * , __off64_t  , int  ) ;
//#line  500
extern  __attribute__((__nothrow__)) void _IO_free_backup_area(_IO_FILE * ) ;
//#line  145 "/usr/include/stdio.h"
extern struct _IO_FILE *stdin ;
//#line  146
extern struct _IO_FILE *stdout ;
//#line  147
extern struct _IO_FILE *stderr ;
//#line  157
extern  __attribute__((__nothrow__)) int remove(char const   *__filename ) ;
//#line  159
extern  __attribute__((__nothrow__)) int rename(char const   *__old , char const   *__new ) ;
//#line  164
extern  __attribute__((__nothrow__)) int renameat(int __oldfd , char const   *__old ,
                                                  int __newfd , char const   *__new ) ;
//#line  174
extern FILE *tmpfile(void) ;
//#line  188
extern  __attribute__((__nothrow__)) char *tmpnam(char *__s ) ;
//#line  194
extern  __attribute__((__nothrow__)) char *tmpnam_r(char *__s ) ;
//#line  206
extern  __attribute__((__nothrow__)) char *tempnam(char const   *__dir , char const   *__pfx )  __attribute__((__malloc__)) ;
//#line  216
extern int fclose(FILE *__stream ) ;
//#line  221
extern int fflush(FILE *__stream ) ;
//#line  231
extern int fflush_unlocked(FILE *__stream ) ;
//#line  251
extern FILE *fopen(char const   * __restrict  __filename , char const   * __restrict  __modes ) ;
//#line  257
extern FILE *freopen(char const   * __restrict  __filename , char const   * __restrict  __modes ,
                     FILE * __restrict  __stream ) ;
//#line  285
extern  __attribute__((__nothrow__)) FILE *fdopen(int __fd , char const   *__modes ) ;
//#line  298
extern  __attribute__((__nothrow__)) FILE *fmemopen(void *__s , size_t __len , char const   *__modes ) ;
//#line  304
extern  __attribute__((__nothrow__)) FILE *open_memstream(char **__bufloc , size_t *__sizeloc ) ;
//#line  311
extern  __attribute__((__nothrow__)) void setbuf(FILE * __restrict  __stream , char * __restrict  __buf ) ;
//#line  315
extern  __attribute__((__nothrow__)) int setvbuf(FILE * __restrict  __stream , char * __restrict  __buf ,
                                                 int __modes , size_t __n ) ;
//#line  322
extern  __attribute__((__nothrow__)) void setbuffer(FILE * __restrict  __stream ,
                                                    char * __restrict  __buf , size_t __size ) ;
//#line  326
extern  __attribute__((__nothrow__)) void setlinebuf(FILE *__stream ) ;
//#line  335
extern int fprintf(FILE * __restrict  __stream , char const   * __restrict  __format 
                   , ...) ;
//#line  341
extern int printf(char const   * __restrict  __format  , ...) ;
//#line  343
extern  __attribute__((__nothrow__)) int sprintf(char * __restrict  __s , char const   * __restrict  __format 
                                                 , ...) ;
//#line  350
extern int vfprintf(FILE * __restrict  __s , char const   * __restrict  __format ,
                    __gnuc_va_list __arg ) ;
//#line  356
extern int vprintf(char const   * __restrict  __format , __gnuc_va_list __arg ) ;
//#line  358
extern  __attribute__((__nothrow__)) int vsprintf(char * __restrict  __s , char const   * __restrict  __format ,
                                                  __gnuc_va_list __arg ) ;
//#line  365
extern  __attribute__((__nothrow__)) int ( /* format attribute */  snprintf)(char * __restrict  __s ,
                                                                             size_t __maxlen ,
                                                                             char const   * __restrict  __format 
                                                                             , ...) ;
//#line  369
extern  __attribute__((__nothrow__)) int ( /* format attribute */  vsnprintf)(char * __restrict  __s ,
                                                                              size_t __maxlen ,
                                                                              char const   * __restrict  __format ,
                                                                              __gnuc_va_list __arg ) ;
//#line  396
extern int ( /* format attribute */  vdprintf)(int __fd , char const   * __restrict  __fmt ,
                                               __gnuc_va_list __arg ) ;
//#line  399
extern int ( /* format attribute */  dprintf)(int __fd , char const   * __restrict  __fmt 
                                              , ...) ;
//#line  409
extern int fscanf(FILE * __restrict  __stream , char const   * __restrict  __format 
                  , ...)  __asm__("__isoc99_fscanf")  ;
//#line  415
extern int scanf(char const   * __restrict  __format  , ...)  __asm__("__isoc99_scanf")  ;
//#line  417
extern  __attribute__((__nothrow__)) int sscanf(char const   * __restrict  __s , char const   * __restrict  __format 
                                                , ...)  __asm__("__isoc99_sscanf")  ;
//#line  455
extern int ( /* format attribute */  vfscanf)(FILE * __restrict  __s , char const   * __restrict  __format ,
                                              __gnuc_va_list __arg )  __asm__("__isoc99_vfscanf")  ;
//#line  463
extern int ( /* format attribute */  vscanf)(char const   * __restrict  __format ,
                                             __gnuc_va_list __arg )  __asm__("__isoc99_vscanf")  ;
//#line  467
extern  __attribute__((__nothrow__)) int ( /* format attribute */  vsscanf)(char const   * __restrict  __s ,
                                                                            char const   * __restrict  __format ,
                                                                            __gnuc_va_list __arg )  __asm__("__isoc99_vsscanf")  ;
//#line  515
extern int fgetc(FILE *__stream ) ;
//#line  516
extern int getc(FILE *__stream ) ;
//#line  522
extern int getchar(void) ;
//#line  534
extern int getc_unlocked(FILE *__stream ) ;
//#line  535
extern int getchar_unlocked(void) ;
//#line  545
extern int fgetc_unlocked(FILE *__stream ) ;
//#line  557
extern int fputc(int __c , FILE *__stream ) ;
//#line  558
extern int putc(int __c , FILE *__stream ) ;
//#line  564
extern int putchar(int __c ) ;
//#line  578
extern int fputc_unlocked(int __c , FILE *__stream ) ;
//#line  586
extern int putc_unlocked(int __c , FILE *__stream ) ;
//#line  587
extern int putchar_unlocked(int __c ) ;
//#line  594
extern int getw(FILE *__stream ) ;
//#line  597
extern int putw(int __w , FILE *__stream ) ;
//#line  606
extern char *fgets(char * __restrict  __s , int __n , FILE * __restrict  __stream ) ;
//#line  614
extern char *gets(char *__s ) ;
//#line  640
extern __ssize_t __getdelim(char ** __restrict  __lineptr , size_t * __restrict  __n ,
                            int __delimiter , FILE * __restrict  __stream ) ;
//#line  643
extern __ssize_t getdelim(char ** __restrict  __lineptr , size_t * __restrict  __n ,
                          int __delimiter , FILE * __restrict  __stream ) ;
//#line  653
extern __ssize_t getline(char ** __restrict  __lineptr , size_t * __restrict  __n ,
                         FILE * __restrict  __stream ) ;
//#line  664
extern int fputs(char const   * __restrict  __s , FILE * __restrict  __stream ) ;
//#line  670
extern int puts(char const   *__s ) ;
//#line  677
extern int ungetc(int __c , FILE *__stream ) ;
//#line  684
extern size_t fread(void * __restrict  __ptr , size_t __size , size_t __n , FILE * __restrict  __stream ) ;
//#line  690
extern size_t fwrite(void const   * __restrict  __ptr , size_t __size , size_t __n ,
                     FILE * __restrict  __s ) ;
//#line  712
extern size_t fread_unlocked(void * __restrict  __ptr , size_t __size , size_t __n ,
                             FILE * __restrict  __stream ) ;
//#line  714
extern size_t fwrite_unlocked(void const   * __restrict  __ptr , size_t __size , size_t __n ,
                              FILE * __restrict  __stream ) ;
//#line  724
extern int fseek(FILE *__stream , long __off , int __whence ) ;
//#line  729
extern long ftell(FILE *__stream ) ;
//#line  734
extern void rewind(FILE *__stream ) ;
//#line  748
extern int fseeko(FILE *__stream , __off_t __off , int __whence ) ;
//#line  753
extern __off_t ftello(FILE *__stream ) ;
//#line  773
extern int fgetpos(FILE * __restrict  __stream , fpos_t * __restrict  __pos ) ;
//#line  778
extern int fsetpos(FILE *__stream , fpos_t const   *__pos ) ;
//#line  801
extern  __attribute__((__nothrow__)) void clearerr(FILE *__stream ) ;
//#line  803
extern  __attribute__((__nothrow__)) int feof(FILE *__stream ) ;
//#line  805
extern  __attribute__((__nothrow__)) int ferror(FILE *__stream ) ;
//#line  810
extern  __attribute__((__nothrow__)) void clearerr_unlocked(FILE *__stream ) ;
//#line  811
extern  __attribute__((__nothrow__)) int feof_unlocked(FILE *__stream ) ;
//#line  812
extern  __attribute__((__nothrow__)) int ferror_unlocked(FILE *__stream ) ;
//#line  821
extern void perror(char const   *__s ) ;
//#line  27 "/usr/include/bits/sys_errlist.h"
extern int sys_nerr ;
//#line  28
extern char const   * const  sys_errlist[] ;
//#line  833 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) int fileno(FILE *__stream ) ;
//#line  838
extern  __attribute__((__nothrow__)) int fileno_unlocked(FILE *__stream ) ;
//#line  848
extern FILE *popen(char const   *__command , char const   *__modes ) ;
//#line  854
extern int pclose(FILE *__stream ) ;
//#line  860
extern  __attribute__((__nothrow__)) char *ctermid(char *__s ) ;
//#line  888
extern  __attribute__((__nothrow__)) void flockfile(FILE *__stream ) ;
//#line  892
extern  __attribute__((__nothrow__)) int ftrylockfile(FILE *__stream ) ;
//#line  895
extern  __attribute__((__nothrow__)) void funlockfile(FILE *__stream ) ;
//#line  2879 "./include/spu/spu_internals.h"
__inline static float __attribute__((__spu_vector__))  ( __attribute__((__always_inline__)) spu_re)(float __attribute__((__spu_vector__))  ra ) ;
//#line  2880
__inline static float __attribute__((__spu_vector__))  ( __attribute__((__always_inline__)) spu_rsqrte)(float __attribute__((__spu_vector__))  ra ) ;
//#line  2882 "./include/spu/spu_internals.h"
__inline static float __attribute__((__spu_vector__))  ( __attribute__((__always_inline__)) spu_re)(float __attribute__((__spu_vector__))  ra ) 
{ signed char __attribute__((__spu_vector__))  tmp ;
  float __attribute__((__spu_vector__))  tmp___0 ;

  {
//#line  2885
  tmp = __builtin_si_frest((signed char __attribute__((__spu_vector__))  )ra);
//#line  2885
  tmp___0 = (float __attribute__((__spu_vector__))  )__builtin_si_fi((signed char __attribute__((__spu_vector__))  )ra,
                                                                     tmp);
//#line  2885
  return (tmp___0);
}
}
//#line  2887 "./include/spu/spu_internals.h"
__inline static float __attribute__((__spu_vector__))  ( __attribute__((__always_inline__)) spu_rsqrte)(float __attribute__((__spu_vector__))  ra ) 
{ signed char __attribute__((__spu_vector__))  tmp ;
  float __attribute__((__spu_vector__))  tmp___0 ;

  {
//#line  2890
  tmp = __builtin_si_frsqest((signed char __attribute__((__spu_vector__))  )ra);
//#line  2890
  tmp___0 = (float __attribute__((__spu_vector__))  )__builtin_si_fi((signed char __attribute__((__spu_vector__))  )ra,
                                                                     tmp);
//#line  2890
  return (tmp___0);
}
}
//#line  2894
__inline static void ( __attribute__((__always_inline__)) spu_mfcdma32)(void volatile   *ls ,
                                                                        unsigned int ea ,
                                                                        unsigned int size ,
                                                                        unsigned int tagid ,
                                                                        unsigned int cmd ) ;
//#line  2895
__inline static void ( __attribute__((__always_inline__)) spu_mfcdma64)(void volatile   *ls ,
                                                                        unsigned int eahi ,
                                                                        unsigned int ealow ,
                                                                        unsigned int size ,
                                                                        unsigned int tagid ,
                                                                        unsigned int cmd ) ;
//#line  2896
__inline static unsigned int ( __attribute__((__always_inline__)) spu_mfcstat)(unsigned int type ) ;
//#line  2898 "./include/spu/spu_internals.h"
__inline static void ( __attribute__((__always_inline__)) spu_mfcdma32)(void volatile   *ls ,
                                                                        unsigned int ea ,
                                                                        unsigned int size ,
                                                                        unsigned int tagid ,
                                                                        unsigned int cmd ) 
{ signed char __attribute__((__spu_vector__))  tmp ;
  signed char __attribute__((__spu_vector__))  tmp___0 ;
  signed char __attribute__((__spu_vector__))  tmp___1 ;
  signed char __attribute__((__spu_vector__))  tmp___2 ;
  signed char __attribute__((__spu_vector__))  tmp___3 ;

  {
//#line  2901
  tmp = __builtin_si_from_ptr((void *)ls);
//#line  2901
  __builtin_si_wrch(16, tmp);
//#line  2902
  tmp___0 = __builtin_si_from_uint(ea);
//#line  2902
  __builtin_si_wrch(18, tmp___0);
//#line  2903
  tmp___1 = __builtin_si_from_uint(size);
//#line  2903
  __builtin_si_wrch(19, tmp___1);
//#line  2904
  tmp___2 = __builtin_si_from_uint(tagid);
//#line  2904
  __builtin_si_wrch(20, tmp___2);
//#line  2905
  tmp___3 = __builtin_si_from_uint(cmd);
//#line  2905
  __builtin_si_wrch(21, tmp___3);
//#line  2906
  return;
}
}
//#line  2907 "./include/spu/spu_internals.h"
__inline static void ( __attribute__((__always_inline__)) spu_mfcdma64)(void volatile   *ls ,
                                                                        unsigned int eahi ,
                                                                        unsigned int ealow ,
                                                                        unsigned int size ,
                                                                        unsigned int tagid ,
                                                                        unsigned int cmd ) 
{ signed char __attribute__((__spu_vector__))  tmp ;
  signed char __attribute__((__spu_vector__))  tmp___0 ;
  signed char __attribute__((__spu_vector__))  tmp___1 ;
  signed char __attribute__((__spu_vector__))  tmp___2 ;
  signed char __attribute__((__spu_vector__))  tmp___3 ;
  signed char __attribute__((__spu_vector__))  tmp___4 ;

  {
//#line  2910
  tmp = __builtin_si_from_ptr((void *)ls);
//#line  2910
  __builtin_si_wrch(16, tmp);
//#line  2911
  tmp___0 = __builtin_si_from_uint(eahi);
//#line  2911
  __builtin_si_wrch(17, tmp___0);
//#line  2912
  tmp___1 = __builtin_si_from_uint(ealow);
//#line  2912
  __builtin_si_wrch(18, tmp___1);
//#line  2913
  tmp___2 = __builtin_si_from_uint(size);
//#line  2913
  __builtin_si_wrch(19, tmp___2);
//#line  2914
  tmp___3 = __builtin_si_from_uint(tagid);
//#line  2914
  __builtin_si_wrch(20, tmp___3);
//#line  2915
  tmp___4 = __builtin_si_from_uint(cmd);
//#line  2915
  __builtin_si_wrch(21, tmp___4);
//#line  2916
  return;
}
}
//#line  2917 "./include/spu/spu_internals.h"
__inline static unsigned int ( __attribute__((__always_inline__)) spu_mfcstat)(unsigned int type ) 
{ signed char __attribute__((__spu_vector__))  tmp ;
  signed char __attribute__((__spu_vector__))  tmp___0 ;
  unsigned int tmp___1 ;

  {
//#line  2920
  tmp = __builtin_si_from_uint(type);
//#line  2920
  __builtin_si_wrch(23, tmp);
//#line  2921
  tmp___0 = __builtin_si_rdch(24);
//#line  2921
  tmp___1 = __builtin_si_to_uint(tmp___0);
//#line  2921
  return (tmp___1);
}
}
//#line  297 "./include/spu/spu_mfcio.h"
__inline static unsigned int ( __attribute__((__always_inline__)) mfc_begin_critical_section)(void) ;
//#line  300 "./include/spu/spu_mfcio.h"
__inline static unsigned int ( __attribute__((__always_inline__)) mfc_begin_critical_section)(void) 
{ 

  {
//#line  308
  return (0U);
}
}
//#line  312
__inline static void ( __attribute__((__always_inline__)) mfc_end_critical_section)(unsigned int __status  __attribute__((__unused__)) ) ;
//#line  315 "./include/spu/spu_mfcio.h"
__inline static void ( __attribute__((__always_inline__)) mfc_end_critical_section)(unsigned int __status  __attribute__((__unused__)) ) 
{ 

  {
//#line  322
  return;
}
}
//#line  338
extern unsigned int __mfc_tag_reserve(void) ;
//#line  339
extern unsigned int __mfc_tag_release(unsigned int  ) ;
//#line  340
extern unsigned int __mfc_multi_tag_reserve(unsigned int  ) ;
//#line  341
extern unsigned int __mfc_multi_tag_release(unsigned int  , unsigned int  ) ;
//#line  35 "include/tpc_spe.h"
extern int execute_task(queue_entry_t *ex_task , tpc_spe_task_state_t *task_info ) ;
//#line  47 "tpc_s2s.h"
extern struct tpc_spe_statistics_t *G_spe_stats[16U] ;
int execute_task(queue_entry_t *ex_task , tpc_spe_task_state_t *task_info ) 
{ int exit ;
  void *__cil_tmp4 ;
  double *__cil_tmp5 ;
  double *__cil_tmp6 ;
  double *__cil_tmp7 ;
  struct FFTsteps23args *__cil_tmp8 ;
  void *__cil_tmp9 ;
  double *__cil_tmp10 ;
  double *__cil_tmp11 ;
  struct FFTsteps23args *__cil_tmp12 ;

  {
  exit = 0;
  switch (ex_task->funcid) {
  case 0: 
  __cil_tmp4 = task_info->ls_addr;
  __cil_tmp5 = (double *)__cil_tmp4;
  __cil_tmp4 += ex_task->arguments[0].size;
  __cil_tmp6 = (double *)__cil_tmp4;
  __cil_tmp4 += ex_task->arguments[1].size;
  __cil_tmp7 = (double *)__cil_tmp4;
  __cil_tmp4 += ex_task->arguments[2].size;
  __cil_tmp8 = (struct FFTsteps23args *)__cil_tmp4;
  FFTsteps23(__cil_tmp5, __cil_tmp6, __cil_tmp7, __cil_tmp8);
  break;
  case 1: 
  __cil_tmp9 = task_info->ls_addr;
  __cil_tmp10 = (double *)__cil_tmp9;
  __cil_tmp9 += ex_task->arguments[0].size;
  __cil_tmp11 = (double *)__cil_tmp9;
  __cil_tmp9 += ex_task->arguments[1].size;
  __cil_tmp12 = (struct FFTsteps23args *)__cil_tmp9;
  FFTsteps5(__cil_tmp10, __cil_tmp11, __cil_tmp12);
  break;
  default: 
  exit = 1;
  break;
  }
  task_info->state = 3;
  return (exit);
}
}
