/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Linear Algebra Data and Routines File                            */
/*                                                                  */
/* Generated by KPP-2.2 symbolic chemistry Kinetics PreProcessor    */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : saprc99_LinearAlgebra.c                   */
/* Time                 : Wed Jan  2 14:34:04 2008                  */
/* Working directory    : /home/jlinford/workspace/fixedgrid/serial/chem */
/* Equation file        : saprc99.kpp                               */
/* Output root filename : saprc99                                   */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "saprc99_Parameters.h"
#include "saprc99_Global.h"
#include "saprc99_Sparse.h"

#if DO_CHEMISTRY == 1

/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* SPARSE_UTIL - SPARSE utility functions                           */
/*   Arguments :                                                    */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


int KppDecomp( double *JVS )
{
double W[74];
double a;
int k, kk, j, jj;

  for( k = 0; k < 74; k++ ) {
    if( JVS[ LU_DIAG[k] ] == 0.0 ) return k+1;
    for( kk = LU_CROW[k]; kk < LU_CROW[k+1]; kk++ )
      W[ LU_ICOL[kk] ] = JVS[kk];
    for( kk = LU_CROW[k]; kk < LU_DIAG[k]; kk++ ) {
      j = LU_ICOL[kk];
      a = -W[j] / JVS[ LU_DIAG[j] ];
      W[j] = -a;
      for( jj = LU_DIAG[j]+1; jj < LU_CROW[j+1]; jj++ )
        W[ LU_ICOL[jj] ] += a*JVS[jj];
    }
    for( kk = LU_CROW[k]; kk < LU_CROW[k+1]; kk++ )
      JVS[kk] = W[ LU_ICOL[kk] ];
  }
  return 0;
}

/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	Sparse LU factorization, complex
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
int KppDecompCmplxR( double JVSR[], double JVSI[] )
{
   double WR[NVAR], WI[NVAR];
   double ar, ai, den;
   int k, kk, j, jj;

   for( k = 0; k < NVAR; k++ ) {
	if( JVSR[ LU_DIAG[k] ] == 0.0 ) return k+1;
	if( JVSI[ LU_DIAG[k] ] == 0.0 ) return k+1;
	for( kk = LU_CROW[k]; kk < LU_CROW[k+1]; kk++ ) {
		WR[ LU_ICOL[kk] ] = JVSR[kk];
		WI[ LU_ICOL[kk] ] = JVSI[kk];
	}
	for( kk = LU_CROW[k]; kk < LU_DIAG[k]; kk++ ) {
	   j = LU_ICOL[kk];
	   den = JVSR[LU_DIAG[j]]*JVSR[LU_DIAG[j]] + JVSI[LU_DIAG[j]]*JVSI[LU_DIAG[j]];
	   ar = -(WR[j]*JVSR[LU_DIAG[j]] + WI[j]*JVSI[LU_DIAG[j]])/den;
	   ai = -(WI[j]*JVSR[LU_DIAG[j]] - WR[j]*JVSI[LU_DIAG[j]])/den;
	   WR[j] = -ar;
	   WI[j] = -ai;
	   for( jj = LU_DIAG[j]+1; jj < LU_CROW[j+1]; jj++ ) {
		   WR[ LU_ICOL[jj] ] = WR[ LU_ICOL[jj] ] + ar*JVSR[jj] - ai*JVSI[jj];
		   WI[ LU_ICOL[jj] ] = WI[ LU_ICOL[jj] ] + ar*JVSI[jj] + ai*JVSR[jj];
	   }
	}
	for( kk = LU_CROW[k]; kk < LU_CROW[k+1]; kk++ ) {
	   JVSR[kk] = WR[ LU_ICOL[kk] ];
	   JVSI[kk] = WI[ LU_ICOL[kk] ];
	}
   }
   return 0;
}

/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	Complex sparse solve subroutine using indirect addressing
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
void KppSolveCmplxR(double JVSR[], double JVSI[], double XR[], double XI[])
{
   int i, j;
   double sumr, sumi, den;

   for ( i = 0; i < NVAR; i++ ) {
	for ( j = LU_CROW[i]; j < LU_DIAG[i]; j++ ) {
	   XR[i] = XR[i] - (JVSR[j]*XR[LU_ICOL[j]] - JVSI[j]*XI[LU_ICOL[j]]);
	   XI[i] = XI[i] - (JVSR[j]*XI[LU_ICOL[j]] + JVSI[j]*XR[LU_ICOL[j]]);
	}
   }
   
   for ( i = NVAR-1; i >= 0; i-- ) {
	sumr = XR[i];
	sumi = XI[i];
	for ( j = LU_DIAG[i]+1; j < LU_CROW[i+1]; j++) {
	   sumr = sumr - (JVSR[j]*XR[LU_ICOL[j]] - JVSI[j]*XI[LU_ICOL[j]]);
	   sumi = sumi - (JVSR[j]*XI[LU_ICOL[j]] + JVSI[j]*XR[LU_ICOL[j]]);
	}
	den = JVSR[LU_DIAG[i]]*JVSR[LU_DIAG[i]] + JVSI[LU_DIAG[i]]*JVSI[LU_DIAG[i]];
  	XR[i] = (sumr*JVSR[LU_DIAG[i]] + sumi*JVSI[LU_DIAG[i]])/den; 
  	XI[i] = (sumi*JVSR[LU_DIAG[i]] - sumr*JVSI[LU_DIAG[i]])/den;
   }
}
/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	END FUNCTION KppSolveCmplxR
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
/* End of SPARSE_UTIL function                                      */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* KppSolve - sparse back substitution                              */
/*   Arguments :                                                    */
/*      JVS       - sparse Jacobian of variables                    */
/*      X         - Vector for variables                            */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void KppSolve( 
  double JVS[],                          /* sparse Jacobian of variables */
  double X[]                             /* Vector for variables */
)
{
  X[21] = X[21]-JVS[91]*X[20];
  X[31] = X[31]-JVS[125]*X[23]-JVS[126]*X[30];
  X[32] = X[32]-JVS[129]*X[23]-JVS[130]*X[30];
  X[33] = X[33]-JVS[133]*X[23]-JVS[134]*X[30];
  X[34] = X[34]-JVS[138]*X[23]-JVS[139]*X[30];
  X[35] = X[35]-JVS[143]*X[27];
  X[37] = X[37]-JVS[154]*X[23]-JVS[155]*X[30];
  X[38] = X[38]-JVS[161]*X[30];
  X[39] = X[39]-JVS[167]*X[19]-JVS[168]*X[29]-JVS[169]*X[31]-JVS[170]
         *X[32]-JVS[171]*X[34];
  X[40] = X[40]-JVS[190]*X[23]-JVS[191]*X[30]-JVS[192]*X[31]-JVS[193]
         *X[32]-JVS[194]*X[33];
  X[41] = X[41]-JVS[202]*X[19]-JVS[203]*X[20]-JVS[204]*X[21]-JVS[205]
         *X[22]-JVS[206]*X[29];
  X[42] = X[42]-JVS[216]*X[17]-JVS[217]*X[33]-JVS[218]*X[35]-JVS[219]
         *X[37]-JVS[220]*X[38]-JVS[221]*X[40];
  X[44] = X[44]-JVS[242]*X[19]-JVS[243]*X[23]-JVS[244]*X[30]-JVS[245]
         *X[31]-JVS[246]*X[32]-JVS[247]*X[34]-JVS[248]*X[38]-JVS[249]
         *X[43];
  X[45] = X[45]-JVS[259]*X[33]-JVS[260]*X[38];
  X[47] = X[47]-JVS[276]*X[20]-JVS[277]*X[22]-JVS[278]*X[29]-JVS[279]
         *X[31]-JVS[280]*X[32]-JVS[281]*X[41]-JVS[282]*X[46];
  X[49] = X[49]-JVS[310]*X[46];
  X[51] = X[51]-JVS[322]*X[46];
  X[53] = X[53]-JVS[334]*X[46]-JVS[335]*X[52];
  X[54] = X[54]-JVS[341]*X[10]-JVS[342]*X[20]-JVS[343]*X[22]-JVS[344]
         *X[29]-JVS[345]*X[43]-JVS[346]*X[50]-JVS[347]*X[51]-JVS[348]
         *X[52];
  X[55] = X[55]-JVS[363]*X[19]-JVS[364]*X[20]-JVS[365]*X[22]-JVS[366]
         *X[25]-JVS[367]*X[26]-JVS[368]*X[28]-JVS[369]*X[29]-JVS[370]
         *X[41]-JVS[371]*X[43]-JVS[372]*X[44]-JVS[373]*X[45]-JVS[374]
         *X[46]-JVS[375]*X[48]-JVS[376]*X[49]-JVS[377]*X[50]-JVS[378]
         *X[51]-JVS[379]*X[52]-JVS[380]*X[53];
  X[56] = X[56]-JVS[399]*X[21]-JVS[400]*X[48]-JVS[401]*X[50]-JVS[402]
         *X[51]-JVS[403]*X[52];
  X[57] = X[57]-JVS[412]*X[9]-JVS[413]*X[43]-JVS[414]*X[46]-JVS[415]
         *X[48]-JVS[416]*X[49]-JVS[417]*X[50]-JVS[418]*X[52]-JVS[419]
         *X[53];
  X[58] = X[58]-JVS[426]*X[19]-JVS[427]*X[20]-JVS[428]*X[22]-JVS[429]
         *X[29]-JVS[430]*X[31]-JVS[431]*X[32]-JVS[432]*X[34]-JVS[433]
         *X[36]-JVS[434]*X[43]-JVS[435]*X[48]-JVS[436]*X[49]-JVS[437]
         *X[50]-JVS[438]*X[51]-JVS[439]*X[52]-JVS[440]*X[53]-JVS[441]
         *X[56]-JVS[442]*X[57];
  X[59] = X[59]-JVS[454]*X[20]-JVS[455]*X[22]-JVS[456]*X[29]-JVS[457]
         *X[49]-JVS[458]*X[50]-JVS[459]*X[51]-JVS[460]*X[52]-JVS[461]
         *X[53]-JVS[462]*X[56]-JVS[463]*X[57];
  X[60] = X[60]-JVS[474]*X[22]-JVS[475]*X[29]-JVS[476]*X[30]-JVS[477]
         *X[46]-JVS[478]*X[48]-JVS[479]*X[50]-JVS[480]*X[51]-JVS[481]
         *X[52]-JVS[482]*X[53]-JVS[483]*X[56]-JVS[484]*X[57];
  X[61] = X[61]-JVS[497]*X[34]-JVS[498]*X[43]-JVS[499]*X[46]-JVS[500]
         *X[48]-JVS[501]*X[49]-JVS[502]*X[50]-JVS[503]*X[51]-JVS[504]
         *X[52]-JVS[505]*X[53]-JVS[506]*X[57];
  X[62] = X[62]-JVS[517]*X[8]-JVS[518]*X[16]-JVS[519]*X[18]-JVS[520]
         *X[19]-JVS[521]*X[23]-JVS[522]*X[24]-JVS[523]*X[25]-JVS[524]
         *X[26]-JVS[525]*X[27]-JVS[526]*X[28]-JVS[527]*X[30]-JVS[528]
         *X[31]-JVS[529]*X[32]-JVS[530]*X[34]-JVS[531]*X[35]-JVS[532]
         *X[36]-JVS[533]*X[39]-JVS[534]*X[40]-JVS[535]*X[43]-JVS[536]
         *X[44]-JVS[537]*X[45]-JVS[538]*X[46]-JVS[539]*X[48]-JVS[540]
         *X[49]-JVS[541]*X[50]-JVS[542]*X[51]-JVS[543]*X[52]-JVS[544]
         *X[53]-JVS[545]*X[54]-JVS[546]*X[55]-JVS[547]*X[56]-JVS[548]
         *X[57]-JVS[549]*X[58]-JVS[550]*X[59]-JVS[551]*X[60]-JVS[552]
         *X[61];
  X[63] = X[63]-JVS[565]*X[19]-JVS[566]*X[20]-JVS[567]*X[22]-JVS[568]
         *X[23]-JVS[569]*X[29]-JVS[570]*X[30]-JVS[571]*X[46]-JVS[572]
         *X[48]-JVS[573]*X[50]-JVS[574]*X[51]-JVS[575]*X[52]-JVS[576]
         *X[53]-JVS[577]*X[56]-JVS[578]*X[57]-JVS[579]*X[58]-JVS[580]
         *X[59]-JVS[581]*X[60]-JVS[582]*X[61]-JVS[583]*X[62];
  X[64] = X[64]-JVS[595]*X[15]-JVS[596]*X[46]-JVS[597]*X[49]-JVS[598]
         *X[51]-JVS[599]*X[52]-JVS[600]*X[53]-JVS[601]*X[57]-JVS[602]
         *X[61]-JVS[603]*X[62]-JVS[604]*X[63];
  X[65] = X[65]-JVS[615]*X[21]-JVS[616]*X[25]-JVS[617]*X[29]-JVS[618]
         *X[41]-JVS[619]*X[43]-JVS[620]*X[46]-JVS[621]*X[48]-JVS[622]
         *X[50]-JVS[623]*X[52]-JVS[624]*X[53]-JVS[625]*X[54]-JVS[626]
         *X[56]-JVS[627]*X[57]-JVS[628]*X[58]-JVS[629]*X[59]-JVS[630]
         *X[60]-JVS[631]*X[61]-JVS[632]*X[62]-JVS[633]*X[63]-JVS[634]
         *X[64];
  X[66] = X[66]-JVS[644]*X[14]-JVS[645]*X[37]-JVS[646]*X[52]-JVS[647]
         *X[57]-JVS[648]*X[61]-JVS[649]*X[62]-JVS[650]*X[63]-JVS[651]
         *X[64]-JVS[652]*X[65];
  X[67] = X[67]-JVS[661]*X[10]-JVS[662]*X[19]-JVS[663]*X[20]-JVS[664]
         *X[22]-JVS[665]*X[23]-JVS[666]*X[29]-JVS[667]*X[30]-JVS[668]
         *X[31]-JVS[669]*X[32]-JVS[670]*X[33]-JVS[671]*X[34]-JVS[672]
         *X[36]-JVS[673]*X[38]-JVS[674]*X[43]-JVS[675]*X[45]-JVS[676]
         *X[46]-JVS[677]*X[48]-JVS[678]*X[49]-JVS[679]*X[50]-JVS[680]
         *X[51]-JVS[681]*X[52]-JVS[682]*X[53]-JVS[683]*X[56]-JVS[684]
         *X[57]-JVS[685]*X[58]-JVS[686]*X[59]-JVS[687]*X[60]-JVS[688]
         *X[61]-JVS[689]*X[62]-JVS[690]*X[63]-JVS[691]*X[64]-JVS[692]
         *X[65]-JVS[693]*X[66];
  X[68] = X[68]-JVS[701]*X[18]-JVS[702]*X[26]-JVS[703]*X[47]-JVS[704]
         *X[48]-JVS[705]*X[50]-JVS[706]*X[52]-JVS[707]*X[53]-JVS[708]
         *X[55]-JVS[709]*X[56]-JVS[710]*X[57]-JVS[711]*X[59]-JVS[712]
         *X[60]-JVS[713]*X[61]-JVS[714]*X[62]-JVS[715]*X[63]-JVS[716]
         *X[64]-JVS[717]*X[65]-JVS[718]*X[66]-JVS[719]*X[67];
  X[69] = X[69]-JVS[726]*X[12]-JVS[727]*X[13]-JVS[728]*X[14]-JVS[729]
         *X[15]-JVS[730]*X[17]-JVS[731]*X[18]-JVS[732]*X[21]-JVS[733]
         *X[24]-JVS[734]*X[26]-JVS[735]*X[27]-JVS[736]*X[35]-JVS[737]
         *X[42]-JVS[738]*X[44]-JVS[739]*X[45]-JVS[740]*X[46]-JVS[741]
         *X[47]-JVS[742]*X[48]-JVS[743]*X[49]-JVS[744]*X[50]-JVS[745]
         *X[51]-JVS[746]*X[52]-JVS[747]*X[53]-JVS[748]*X[54]-JVS[749]
         *X[55]-JVS[750]*X[56]-JVS[751]*X[57]-JVS[752]*X[58]-JVS[753]
         *X[59]-JVS[754]*X[60]-JVS[755]*X[61]-JVS[756]*X[62]-JVS[757]
         *X[63]-JVS[758]*X[64]-JVS[759]*X[65]-JVS[760]*X[66]-JVS[761]
         *X[67]-JVS[762]*X[68];
  X[70] = X[70]-JVS[768]*X[17]-JVS[769]*X[24]-JVS[770]*X[33]-JVS[771]
         *X[35]-JVS[772]*X[37]-JVS[773]*X[38]-JVS[774]*X[40]-JVS[775]
         *X[42]-JVS[776]*X[43]-JVS[777]*X[44]-JVS[778]*X[45]-JVS[779]
         *X[46]-JVS[780]*X[47]-JVS[781]*X[48]-JVS[782]*X[49]-JVS[783]
         *X[50]-JVS[784]*X[51]-JVS[785]*X[52]-JVS[786]*X[53]-JVS[787]
         *X[54]-JVS[788]*X[55]-JVS[789]*X[56]-JVS[790]*X[57]-JVS[791]
         *X[58]-JVS[792]*X[59]-JVS[793]*X[60]-JVS[794]*X[61]-JVS[795]
         *X[62]-JVS[796]*X[63]-JVS[797]*X[64]-JVS[798]*X[65]-JVS[799]
         *X[66]-JVS[800]*X[67]-JVS[801]*X[68]-JVS[802]*X[69];
  X[71] = X[71]-JVS[807]*X[11]-JVS[808]*X[12]-JVS[809]*X[23]-JVS[810]
         *X[29]-JVS[811]*X[31]-JVS[812]*X[32]-JVS[813]*X[40]-JVS[814]
         *X[41]-JVS[815]*X[48]-JVS[816]*X[49]-JVS[817]*X[50]-JVS[818]
         *X[51]-JVS[819]*X[52]-JVS[820]*X[53]-JVS[821]*X[54]-JVS[822]
         *X[56]-JVS[823]*X[57]-JVS[824]*X[58]-JVS[825]*X[59]-JVS[826]
         *X[60]-JVS[827]*X[61]-JVS[828]*X[62]-JVS[829]*X[63]-JVS[830]
         *X[64]-JVS[831]*X[65]-JVS[832]*X[66]-JVS[833]*X[67]-JVS[834]
         *X[68]-JVS[835]*X[69]-JVS[836]*X[70];
  X[72] = X[72]-JVS[840]*X[13]-JVS[841]*X[44]-JVS[842]*X[45]-JVS[843]
         *X[48]-JVS[844]*X[49]-JVS[845]*X[51]-JVS[846]*X[52]-JVS[847]
         *X[53]-JVS[848]*X[57]-JVS[849]*X[58]-JVS[850]*X[59]-JVS[851]
         *X[60]-JVS[852]*X[61]-JVS[853]*X[62]-JVS[854]*X[63]-JVS[855]
         *X[64]-JVS[856]*X[65]-JVS[857]*X[66]-JVS[858]*X[67]-JVS[859]
         *X[68]-JVS[860]*X[69]-JVS[861]*X[70]-JVS[862]*X[71];
  X[73] = X[73]-JVS[865]*X[8]-JVS[866]*X[9]-JVS[867]*X[10]-JVS[868]
         *X[16]-JVS[869]*X[18]-JVS[870]*X[19]-JVS[871]*X[20]-JVS[872]
         *X[22]-JVS[873]*X[23]-JVS[874]*X[24]-JVS[875]*X[25]-JVS[876]
         *X[28]-JVS[877]*X[29]-JVS[878]*X[30]-JVS[879]*X[31]-JVS[880]
         *X[32]-JVS[881]*X[33]-JVS[882]*X[34]-JVS[883]*X[36]-JVS[884]
         *X[37]-JVS[885]*X[38]-JVS[886]*X[39]-JVS[887]*X[40]-JVS[888]
         *X[41]-JVS[889]*X[42]-JVS[890]*X[43]-JVS[891]*X[44]-JVS[892]
         *X[45]-JVS[893]*X[46]-JVS[894]*X[48]-JVS[895]*X[49]-JVS[896]
         *X[50]-JVS[897]*X[51]-JVS[898]*X[52]-JVS[899]*X[53]-JVS[900]
         *X[54]-JVS[901]*X[55]-JVS[902]*X[56]-JVS[903]*X[57]-JVS[904]
         *X[58]-JVS[905]*X[59]-JVS[906]*X[60]-JVS[907]*X[61]-JVS[908]
         *X[62]-JVS[909]*X[63]-JVS[910]*X[64]-JVS[911]*X[65]-JVS[912]
         *X[66]-JVS[913]*X[67]-JVS[914]*X[68]-JVS[915]*X[69]-JVS[916]
         *X[70]-JVS[917]*X[71]-JVS[918]*X[72];
  X[73] = X[73]/JVS[919];
  X[72] = (X[72]-JVS[864]*X[73])/(JVS[863]);
  X[71] = (X[71]-JVS[838]*X[72]-JVS[839]*X[73])/(JVS[837]);
  X[70] = (X[70]-JVS[804]*X[71]-JVS[805]*X[72]-JVS[806]*X[73])
         /(JVS[803]);
  X[69] = (X[69]-JVS[764]*X[70]-JVS[765]*X[71]-JVS[766]*X[72]-JVS[767]
         *X[73])/(JVS[763]);
  X[68] = (X[68]-JVS[721]*X[69]-JVS[722]*X[70]-JVS[723]*X[71]-JVS[724]
         *X[72]-JVS[725]*X[73])/(JVS[720]);
  X[67] = (X[67]-JVS[695]*X[68]-JVS[696]*X[69]-JVS[697]*X[70]-JVS[698]
         *X[71]-JVS[699]*X[72]-JVS[700]*X[73])/(JVS[694]);
  X[66] = (X[66]-JVS[654]*X[67]-JVS[655]*X[68]-JVS[656]*X[69]-JVS[657]
         *X[70]-JVS[658]*X[71]-JVS[659]*X[72]-JVS[660]*X[73])
         /(JVS[653]);
  X[65] = (X[65]-JVS[636]*X[66]-JVS[637]*X[67]-JVS[638]*X[68]-JVS[639]
         *X[69]-JVS[640]*X[70]-JVS[641]*X[71]-JVS[642]*X[72]-JVS[643]
         *X[73])/(JVS[635]);
  X[64] = (X[64]-JVS[606]*X[65]-JVS[607]*X[66]-JVS[608]*X[67]-JVS[609]
         *X[68]-JVS[610]*X[69]-JVS[611]*X[70]-JVS[612]*X[71]-JVS[613]
         *X[72]-JVS[614]*X[73])/(JVS[605]);
  X[63] = (X[63]-JVS[585]*X[64]-JVS[586]*X[65]-JVS[587]*X[66]-JVS[588]
         *X[67]-JVS[589]*X[68]-JVS[590]*X[69]-JVS[591]*X[70]-JVS[592]
         *X[71]-JVS[593]*X[72]-JVS[594]*X[73])/(JVS[584]);
  X[62] = (X[62]-JVS[554]*X[63]-JVS[555]*X[64]-JVS[556]*X[65]-JVS[557]
         *X[66]-JVS[558]*X[67]-JVS[559]*X[68]-JVS[560]*X[69]-JVS[561]
         *X[70]-JVS[562]*X[71]-JVS[563]*X[72]-JVS[564]*X[73])
         /(JVS[553]);
  X[61] = (X[61]-JVS[508]*X[62]-JVS[509]*X[64]-JVS[510]*X[66]-JVS[511]
         *X[68]-JVS[512]*X[69]-JVS[513]*X[70]-JVS[514]*X[71]-JVS[515]
         *X[72]-JVS[516]*X[73])/(JVS[507]);
  X[60] = (X[60]-JVS[486]*X[61]-JVS[487]*X[63]-JVS[488]*X[65]-JVS[489]
         *X[66]-JVS[490]*X[67]-JVS[491]*X[68]-JVS[492]*X[69]-JVS[493]
         *X[70]-JVS[494]*X[71]-JVS[495]*X[72]-JVS[496]*X[73])
         /(JVS[485]);
  X[59] = (X[59]-JVS[465]*X[60]-JVS[466]*X[61]-JVS[467]*X[63]-JVS[468]
         *X[65]-JVS[469]*X[67]-JVS[470]*X[68]-JVS[471]*X[69]-JVS[472]
         *X[70]-JVS[473]*X[73])/(JVS[464]);
  X[58] = (X[58]-JVS[444]*X[59]-JVS[445]*X[60]-JVS[446]*X[61]-JVS[447]
         *X[62]-JVS[448]*X[63]-JVS[449]*X[67]-JVS[450]*X[68]-JVS[451]
         *X[69]-JVS[452]*X[70]-JVS[453]*X[73])/(JVS[443]);
  X[57] = (X[57]-JVS[421]*X[61]-JVS[422]*X[68]-JVS[423]*X[69]-JVS[424]
         *X[70]-JVS[425]*X[73])/(JVS[420]);
  X[56] = (X[56]-JVS[405]*X[57]-JVS[406]*X[61]-JVS[407]*X[63]-JVS[408]
         *X[68]-JVS[409]*X[69]-JVS[410]*X[70]-JVS[411]*X[73])
         /(JVS[404]);
  X[55] = (X[55]-JVS[382]*X[56]-JVS[383]*X[57]-JVS[384]*X[59]-JVS[385]
         *X[60]-JVS[386]*X[61]-JVS[387]*X[62]-JVS[388]*X[63]-JVS[389]
         *X[64]-JVS[390]*X[65]-JVS[391]*X[66]-JVS[392]*X[67]-JVS[393]
         *X[68]-JVS[394]*X[69]-JVS[395]*X[70]-JVS[396]*X[71]-JVS[397]
         *X[72]-JVS[398]*X[73])/(JVS[381]);
  X[54] = (X[54]-JVS[350]*X[56]-JVS[351]*X[57]-JVS[352]*X[58]-JVS[353]
         *X[59]-JVS[354]*X[60]-JVS[355]*X[61]-JVS[356]*X[64]-JVS[357]
         *X[66]-JVS[358]*X[68]-JVS[359]*X[70]-JVS[360]*X[71]-JVS[361]
         *X[72]-JVS[362]*X[73])/(JVS[349]);
  X[53] = (X[53]-JVS[337]*X[57]-JVS[338]*X[61]-JVS[339]*X[70]-JVS[340]
         *X[73])/(JVS[336]);
  X[52] = (X[52]-JVS[330]*X[57]-JVS[331]*X[61]-JVS[332]*X[70]-JVS[333]
         *X[73])/(JVS[329]);
  X[51] = (X[51]-JVS[324]*X[52]-JVS[325]*X[57]-JVS[326]*X[61]-JVS[327]
         *X[70]-JVS[328]*X[73])/(JVS[323]);
  X[50] = (X[50]-JVS[318]*X[57]-JVS[319]*X[61]-JVS[320]*X[70]-JVS[321]
         *X[73])/(JVS[317]);
  X[49] = (X[49]-JVS[312]*X[52]-JVS[313]*X[57]-JVS[314]*X[61]-JVS[315]
         *X[70]-JVS[316]*X[73])/(JVS[311]);
  X[48] = (X[48]-JVS[306]*X[57]-JVS[307]*X[61]-JVS[308]*X[70]-JVS[309]
         *X[73])/(JVS[305]);
  X[47] = (X[47]-JVS[284]*X[48]-JVS[285]*X[50]-JVS[286]*X[52]-JVS[287]
         *X[53]-JVS[288]*X[56]-JVS[289]*X[57]-JVS[290]*X[59]-JVS[291]
         *X[60]-JVS[292]*X[61]-JVS[293]*X[62]-JVS[294]*X[63]-JVS[295]
         *X[64]-JVS[296]*X[65]-JVS[297]*X[66]-JVS[298]*X[67]-JVS[299]
         *X[68]-JVS[300]*X[69]-JVS[301]*X[70]-JVS[302]*X[71]-JVS[303]
         *X[72]-JVS[304]*X[73])/(JVS[283]);
  X[46] = (X[46]-JVS[272]*X[57]-JVS[273]*X[61]-JVS[274]*X[70]-JVS[275]
         *X[73])/(JVS[271]);
  X[45] = (X[45]-JVS[262]*X[62]-JVS[263]*X[64]-JVS[264]*X[66]-JVS[265]
         *X[68]-JVS[266]*X[69]-JVS[267]*X[70]-JVS[268]*X[71]-JVS[269]
         *X[72]-JVS[270]*X[73])/(JVS[261]);
  X[44] = (X[44]-JVS[251]*X[45]-JVS[252]*X[48]-JVS[253]*X[51]-JVS[254]
         *X[57]-JVS[255]*X[61]-JVS[256]*X[62]-JVS[257]*X[70]-JVS[258]
         *X[73])/(JVS[250]);
  X[43] = (X[43]-JVS[238]*X[57]-JVS[239]*X[61]-JVS[240]*X[70]-JVS[241]
         *X[73])/(JVS[237]);
  X[42] = (X[42]-JVS[223]*X[44]-JVS[224]*X[45]-JVS[225]*X[49]-JVS[226]
         *X[51]-JVS[227]*X[52]-JVS[228]*X[53]-JVS[229]*X[54]-JVS[230]
         *X[55]-JVS[231]*X[58]-JVS[232]*X[61]-JVS[233]*X[62]-JVS[234]
         *X[69]-JVS[235]*X[70]-JVS[236]*X[73])/(JVS[222]);
  X[41] = (X[41]-JVS[208]*X[48]-JVS[209]*X[50]-JVS[210]*X[52]-JVS[211]
         *X[56]-JVS[212]*X[61]-JVS[213]*X[69]-JVS[214]*X[70]-JVS[215]
         *X[73])/(JVS[207]);
  X[40] = (X[40]-JVS[196]*X[49]-JVS[197]*X[51]-JVS[198]*X[53]-JVS[199]
         *X[61]-JVS[200]*X[70]-JVS[201]*X[73])/(JVS[195]);
  X[39] = (X[39]-JVS[173]*X[40]-JVS[174]*X[43]-JVS[175]*X[44]-JVS[176]
         *X[46]-JVS[177]*X[48]-JVS[178]*X[49]-JVS[179]*X[50]-JVS[180]
         *X[51]-JVS[181]*X[52]-JVS[182]*X[53]-JVS[183]*X[54]-JVS[184]
         *X[55]-JVS[185]*X[57]-JVS[186]*X[58]-JVS[187]*X[61]-JVS[188]
         *X[70]-JVS[189]*X[73])/(JVS[172]);
  X[38] = (X[38]-JVS[163]*X[45]-JVS[164]*X[62]-JVS[165]*X[70]-JVS[166]
         *X[73])/(JVS[162]);
  X[37] = (X[37]-JVS[157]*X[52]-JVS[158]*X[61]-JVS[159]*X[70]-JVS[160]
         *X[73])/(JVS[156]);
  X[36] = (X[36]-JVS[150]*X[62]-JVS[151]*X[63]-JVS[152]*X[67]-JVS[153]
         *X[73])/(JVS[149]);
  X[35] = (X[35]-JVS[145]*X[45]-JVS[146]*X[62]-JVS[147]*X[69]-JVS[148]
         *X[70])/(JVS[144]);
  X[34] = (X[34]-JVS[141]*X[61]-JVS[142]*X[73])/(JVS[140]);
  X[33] = (X[33]-JVS[136]*X[70]-JVS[137]*X[73])/(JVS[135]);
  X[32] = (X[32]-JVS[132]*X[73])/(JVS[131]);
  X[31] = (X[31]-JVS[128]*X[73])/(JVS[127]);
  X[30] = (X[30]-JVS[124]*X[73])/(JVS[123]);
  X[29] = (X[29]-JVS[122]*X[73])/(JVS[121]);
  X[28] = (X[28]-JVS[117]*X[63]-JVS[118]*X[65]-JVS[119]*X[67]-JVS[120]
         *X[73])/(JVS[116]);
  X[27] = (X[27]-JVS[112]*X[35]-JVS[113]*X[62]-JVS[114]*X[69]-JVS[115]
         *X[70])/(JVS[111]);
  X[26] = (X[26]-JVS[108]*X[55]-JVS[109]*X[62]-JVS[110]*X[68])
         /(JVS[107]);
  X[25] = (X[25]-JVS[104]*X[62]-JVS[105]*X[65]-JVS[106]*X[73])
         /(JVS[103]);
  X[24] = (X[24]-JVS[100]*X[62]-JVS[101]*X[69]-JVS[102]*X[73])
         /(JVS[99]);
  X[23] = (X[23]-JVS[98]*X[73])/(JVS[97]);
  X[22] = (X[22]-JVS[96]*X[73])/(JVS[95]);
  X[21] = (X[21]-JVS[93]*X[69]-JVS[94]*X[73])/(JVS[92]);
  X[20] = (X[20]-JVS[90]*X[73])/(JVS[89]);
  X[19] = (X[19]-JVS[88]*X[73])/(JVS[87]);
  X[18] = (X[18]-JVS[85]*X[68]-JVS[86]*X[73])/(JVS[84]);
  X[17] = (X[17]-JVS[82]*X[69]-JVS[83]*X[70])/(JVS[81]);
  X[16] = (X[16]-JVS[79]*X[62]-JVS[80]*X[73])/(JVS[78]);
  X[15] = (X[15]-JVS[76]*X[64]-JVS[77]*X[69])/(JVS[75]);
  X[14] = (X[14]-JVS[73]*X[66]-JVS[74]*X[69])/(JVS[72]);
  X[13] = (X[13]-JVS[70]*X[69]-JVS[71]*X[72])/(JVS[69]);
  X[12] = (X[12]-JVS[67]*X[69]-JVS[68]*X[71])/(JVS[66]);
  X[11] = (X[11]-JVS[62]*X[23]-JVS[63]*X[48]-JVS[64]*X[61]-JVS[65]
         *X[73])/(JVS[61]);
  X[10] = (X[10]-JVS[60]*X[73])/(JVS[59]);
  X[9] = (X[9]-JVS[58]*X[61])/(JVS[57]);
  X[8] = (X[8]-JVS[56]*X[73])/(JVS[55]);
  X[7] = (X[7]-JVS[52]*X[27]-JVS[53]*X[37]-JVS[54]*X[69])/(JVS[51]);
  X[6] = (X[6]-JVS[49]*X[27]-JVS[50]*X[69])/(JVS[48]);
  X[5] = (X[5]-JVS[44]*X[62]-JVS[45]*X[64]-JVS[46]*X[66]-JVS[47]*X[72])
        /(JVS[43]);
  X[4] = (X[4]-JVS[41]*X[62]-JVS[42]*X[71])/(JVS[40]);
  X[3] = (X[3]-JVS[27]*X[46]-JVS[28]*X[48]-JVS[29]*X[50]-JVS[30]*X[51]
        -JVS[31]*X[52]-JVS[32]*X[61]-JVS[33]*X[62]-JVS[34]*X[63]
        -JVS[35]*X[64]-JVS[36]*X[65]-JVS[37]*X[66]-JVS[38]*X[67]
        -JVS[39]*X[72])/(JVS[26]);
  X[2] = (X[2]-JVS[18]*X[50]-JVS[19]*X[52]-JVS[20]*X[61]-JVS[21]*X[62]
        -JVS[22]*X[63]-JVS[23]*X[65]-JVS[24]*X[67]-JVS[25]*X[71])
        /(JVS[17]);
  X[1] = (X[1]-JVS[4]*X[19]-JVS[5]*X[26]-JVS[6]*X[43]-JVS[7]*X[46]
        -JVS[8]*X[48]-JVS[9]*X[49]-JVS[10]*X[50]-JVS[11]*X[51]-JVS[12]
        *X[52]-JVS[13]*X[53]-JVS[14]*X[61]-JVS[15]*X[68]-JVS[16]*X[73])
        /(JVS[3]);
  X[0] = (X[0]-JVS[1]*X[8]-JVS[2]*X[73])/(JVS[0]);
}

/* End of KppSolve function                                         */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* KppSolveTR - sparse, transposed back substitution                */
/*   Arguments :                                                    */
/*      JVS       - sparse Jacobian of variables                    */
/*      X         - Vector for variables                            */
/*      XX        - Vector for output variables                     */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void KppSolveTR( 
  double JVS[],                          /* sparse Jacobian of variables */
  double X[],                            /* Vector for variables */
  double XX[]                            /* Vector for output variables */
)
{
  XX[0] = X[0]/JVS[0];
  XX[1] = X[1]/JVS[3];
  XX[2] = X[2]/JVS[17];
  XX[3] = X[3]/JVS[26];
  XX[4] = X[4]/JVS[40];
  XX[5] = X[5]/JVS[43];
  XX[6] = X[6]/JVS[48];
  XX[7] = X[7]/JVS[51];
  XX[8] = (X[8]-JVS[1]*XX[0])/(JVS[55]);
  XX[9] = X[9]/JVS[57];
  XX[10] = X[10]/JVS[59];
  XX[11] = X[11]/JVS[61];
  XX[12] = X[12]/JVS[66];
  XX[13] = X[13]/JVS[69];
  XX[14] = X[14]/JVS[72];
  XX[15] = X[15]/JVS[75];
  XX[16] = X[16]/JVS[78];
  XX[17] = X[17]/JVS[81];
  XX[18] = X[18]/JVS[84];
  XX[19] = (X[19]-JVS[4]*XX[1])/(JVS[87]);
  XX[20] = X[20]/JVS[89];
  XX[21] = X[21]/JVS[92];
  XX[22] = X[22]/JVS[95];
  XX[23] = (X[23]-JVS[62]*XX[11])/(JVS[97]);
  XX[24] = X[24]/JVS[99];
  XX[25] = X[25]/JVS[103];
  XX[26] = (X[26]-JVS[5]*XX[1])/(JVS[107]);
  XX[27] = (X[27]-JVS[49]*XX[6]-JVS[52]*XX[7])/(JVS[111]);
  XX[28] = X[28]/JVS[116];
  XX[29] = X[29]/JVS[121];
  XX[30] = X[30]/JVS[123];
  XX[31] = X[31]/JVS[127];
  XX[32] = X[32]/JVS[131];
  XX[33] = X[33]/JVS[135];
  XX[34] = X[34]/JVS[140];
  XX[35] = (X[35]-JVS[112]*XX[27])/(JVS[144]);
  XX[36] = X[36]/JVS[149];
  XX[37] = (X[37]-JVS[53]*XX[7])/(JVS[156]);
  XX[38] = X[38]/JVS[162];
  XX[39] = X[39]/JVS[172];
  XX[40] = (X[40]-JVS[173]*XX[39])/(JVS[195]);
  XX[41] = X[41]/JVS[207];
  XX[42] = X[42]/JVS[222];
  XX[43] = (X[43]-JVS[6]*XX[1]-JVS[174]*XX[39])/(JVS[237]);
  XX[44] = (X[44]-JVS[175]*XX[39]-JVS[223]*XX[42])/(JVS[250]);
  XX[45] = (X[45]-JVS[145]*XX[35]-JVS[163]*XX[38]-JVS[224]*XX[42]
          -JVS[251]*XX[44])/(JVS[261]);
  XX[46] = (X[46]-JVS[7]*XX[1]-JVS[27]*XX[3]-JVS[176]*XX[39])
          /(JVS[271]);
  XX[47] = X[47]/JVS[283];
  XX[48] = (X[48]-JVS[8]*XX[1]-JVS[28]*XX[3]-JVS[63]*XX[11]-JVS[177]
          *XX[39]-JVS[208]*XX[41]-JVS[252]*XX[44]-JVS[284]*XX[47])
          /(JVS[305]);
  XX[49] = (X[49]-JVS[9]*XX[1]-JVS[178]*XX[39]-JVS[196]*XX[40]-JVS[225]
          *XX[42])/(JVS[311]);
  XX[50] = (X[50]-JVS[10]*XX[1]-JVS[18]*XX[2]-JVS[29]*XX[3]-JVS[179]
          *XX[39]-JVS[209]*XX[41]-JVS[285]*XX[47])/(JVS[317]);
  XX[51] = (X[51]-JVS[11]*XX[1]-JVS[30]*XX[3]-JVS[180]*XX[39]-JVS[197]
          *XX[40]-JVS[226]*XX[42]-JVS[253]*XX[44])/(JVS[323]);
  XX[52] = (X[52]-JVS[12]*XX[1]-JVS[19]*XX[2]-JVS[31]*XX[3]-JVS[157]
          *XX[37]-JVS[181]*XX[39]-JVS[210]*XX[41]-JVS[227]*XX[42]
          -JVS[286]*XX[47]-JVS[312]*XX[49]-JVS[324]*XX[51])/(JVS[329]);
  XX[53] = (X[53]-JVS[13]*XX[1]-JVS[182]*XX[39]-JVS[198]*XX[40]
          -JVS[228]*XX[42]-JVS[287]*XX[47])/(JVS[336]);
  XX[54] = (X[54]-JVS[183]*XX[39]-JVS[229]*XX[42])/(JVS[349]);
  XX[55] = (X[55]-JVS[108]*XX[26]-JVS[184]*XX[39]-JVS[230]*XX[42])
          /(JVS[381]);
  XX[56] = (X[56]-JVS[211]*XX[41]-JVS[288]*XX[47]-JVS[350]*XX[54]
          -JVS[382]*XX[55])/(JVS[404]);
  XX[57] = (X[57]-JVS[185]*XX[39]-JVS[238]*XX[43]-JVS[254]*XX[44]
          -JVS[272]*XX[46]-JVS[289]*XX[47]-JVS[306]*XX[48]-JVS[313]
          *XX[49]-JVS[318]*XX[50]-JVS[325]*XX[51]-JVS[330]*XX[52]
          -JVS[337]*XX[53]-JVS[351]*XX[54]-JVS[383]*XX[55]-JVS[405]
          *XX[56])/(JVS[420]);
  XX[58] = (X[58]-JVS[186]*XX[39]-JVS[231]*XX[42]-JVS[352]*XX[54])
          /(JVS[443]);
  XX[59] = (X[59]-JVS[290]*XX[47]-JVS[353]*XX[54]-JVS[384]*XX[55]
          -JVS[444]*XX[58])/(JVS[464]);
  XX[60] = (X[60]-JVS[291]*XX[47]-JVS[354]*XX[54]-JVS[385]*XX[55]
          -JVS[445]*XX[58]-JVS[465]*XX[59])/(JVS[485]);
  XX[61] = (X[61]-JVS[14]*XX[1]-JVS[20]*XX[2]-JVS[32]*XX[3]-JVS[58]
          *XX[9]-JVS[64]*XX[11]-JVS[141]*XX[34]-JVS[158]*XX[37]
          -JVS[187]*XX[39]-JVS[199]*XX[40]-JVS[212]*XX[41]-JVS[232]
          *XX[42]-JVS[239]*XX[43]-JVS[255]*XX[44]-JVS[273]*XX[46]
          -JVS[292]*XX[47]-JVS[307]*XX[48]-JVS[314]*XX[49]-JVS[319]
          *XX[50]-JVS[326]*XX[51]-JVS[331]*XX[52]-JVS[338]*XX[53]
          -JVS[355]*XX[54]-JVS[386]*XX[55]-JVS[406]*XX[56]-JVS[421]
          *XX[57]-JVS[446]*XX[58]-JVS[466]*XX[59]-JVS[486]*XX[60])
          /(JVS[507]);
  XX[62] = (X[62]-JVS[21]*XX[2]-JVS[33]*XX[3]-JVS[41]*XX[4]-JVS[44]
          *XX[5]-JVS[79]*XX[16]-JVS[100]*XX[24]-JVS[104]*XX[25]
          -JVS[109]*XX[26]-JVS[113]*XX[27]-JVS[146]*XX[35]-JVS[150]
          *XX[36]-JVS[164]*XX[38]-JVS[233]*XX[42]-JVS[256]*XX[44]
          -JVS[262]*XX[45]-JVS[293]*XX[47]-JVS[387]*XX[55]-JVS[447]
          *XX[58]-JVS[508]*XX[61])/(JVS[553]);
  XX[63] = (X[63]-JVS[22]*XX[2]-JVS[34]*XX[3]-JVS[117]*XX[28]-JVS[151]
          *XX[36]-JVS[294]*XX[47]-JVS[388]*XX[55]-JVS[407]*XX[56]
          -JVS[448]*XX[58]-JVS[467]*XX[59]-JVS[487]*XX[60]-JVS[554]
          *XX[62])/(JVS[584]);
  XX[64] = (X[64]-JVS[35]*XX[3]-JVS[45]*XX[5]-JVS[76]*XX[15]-JVS[263]
          *XX[45]-JVS[295]*XX[47]-JVS[356]*XX[54]-JVS[389]*XX[55]
          -JVS[509]*XX[61]-JVS[555]*XX[62]-JVS[585]*XX[63])/(JVS[605]);
  XX[65] = (X[65]-JVS[23]*XX[2]-JVS[36]*XX[3]-JVS[105]*XX[25]-JVS[118]
          *XX[28]-JVS[296]*XX[47]-JVS[390]*XX[55]-JVS[468]*XX[59]
          -JVS[488]*XX[60]-JVS[556]*XX[62]-JVS[586]*XX[63]-JVS[606]
          *XX[64])/(JVS[635]);
  XX[66] = (X[66]-JVS[37]*XX[3]-JVS[46]*XX[5]-JVS[73]*XX[14]-JVS[264]
          *XX[45]-JVS[297]*XX[47]-JVS[357]*XX[54]-JVS[391]*XX[55]
          -JVS[489]*XX[60]-JVS[510]*XX[61]-JVS[557]*XX[62]-JVS[587]
          *XX[63]-JVS[607]*XX[64]-JVS[636]*XX[65])/(JVS[653]);
  XX[67] = (X[67]-JVS[24]*XX[2]-JVS[38]*XX[3]-JVS[119]*XX[28]-JVS[152]
          *XX[36]-JVS[298]*XX[47]-JVS[392]*XX[55]-JVS[449]*XX[58]
          -JVS[469]*XX[59]-JVS[490]*XX[60]-JVS[558]*XX[62]-JVS[588]
          *XX[63]-JVS[608]*XX[64]-JVS[637]*XX[65]-JVS[654]*XX[66])
          /(JVS[694]);
  XX[68] = (X[68]-JVS[15]*XX[1]-JVS[85]*XX[18]-JVS[110]*XX[26]-JVS[265]
          *XX[45]-JVS[299]*XX[47]-JVS[358]*XX[54]-JVS[393]*XX[55]
          -JVS[408]*XX[56]-JVS[422]*XX[57]-JVS[450]*XX[58]-JVS[470]
          *XX[59]-JVS[491]*XX[60]-JVS[511]*XX[61]-JVS[559]*XX[62]
          -JVS[589]*XX[63]-JVS[609]*XX[64]-JVS[638]*XX[65]-JVS[655]
          *XX[66]-JVS[695]*XX[67])/(JVS[720]);
  XX[69] = (X[69]-JVS[50]*XX[6]-JVS[54]*XX[7]-JVS[67]*XX[12]-JVS[70]
          *XX[13]-JVS[74]*XX[14]-JVS[77]*XX[15]-JVS[82]*XX[17]-JVS[93]
          *XX[21]-JVS[101]*XX[24]-JVS[114]*XX[27]-JVS[147]*XX[35]
          -JVS[213]*XX[41]-JVS[234]*XX[42]-JVS[266]*XX[45]-JVS[300]
          *XX[47]-JVS[394]*XX[55]-JVS[409]*XX[56]-JVS[423]*XX[57]
          -JVS[451]*XX[58]-JVS[471]*XX[59]-JVS[492]*XX[60]-JVS[512]
          *XX[61]-JVS[560]*XX[62]-JVS[590]*XX[63]-JVS[610]*XX[64]
          -JVS[639]*XX[65]-JVS[656]*XX[66]-JVS[696]*XX[67]-JVS[721]
          *XX[68])/(JVS[763]);
  XX[70] = (X[70]-JVS[83]*XX[17]-JVS[115]*XX[27]-JVS[136]*XX[33]
          -JVS[148]*XX[35]-JVS[159]*XX[37]-JVS[165]*XX[38]-JVS[188]
          *XX[39]-JVS[200]*XX[40]-JVS[214]*XX[41]-JVS[235]*XX[42]
          -JVS[240]*XX[43]-JVS[257]*XX[44]-JVS[267]*XX[45]-JVS[274]
          *XX[46]-JVS[301]*XX[47]-JVS[308]*XX[48]-JVS[315]*XX[49]
          -JVS[320]*XX[50]-JVS[327]*XX[51]-JVS[332]*XX[52]-JVS[339]
          *XX[53]-JVS[359]*XX[54]-JVS[395]*XX[55]-JVS[410]*XX[56]
          -JVS[424]*XX[57]-JVS[452]*XX[58]-JVS[472]*XX[59]-JVS[493]
          *XX[60]-JVS[513]*XX[61]-JVS[561]*XX[62]-JVS[591]*XX[63]
          -JVS[611]*XX[64]-JVS[640]*XX[65]-JVS[657]*XX[66]-JVS[697]
          *XX[67]-JVS[722]*XX[68]-JVS[764]*XX[69])/(JVS[803]);
  XX[71] = (X[71]-JVS[25]*XX[2]-JVS[42]*XX[4]-JVS[68]*XX[12]-JVS[268]
          *XX[45]-JVS[302]*XX[47]-JVS[360]*XX[54]-JVS[396]*XX[55]
          -JVS[494]*XX[60]-JVS[514]*XX[61]-JVS[562]*XX[62]-JVS[592]
          *XX[63]-JVS[612]*XX[64]-JVS[641]*XX[65]-JVS[658]*XX[66]
          -JVS[698]*XX[67]-JVS[723]*XX[68]-JVS[765]*XX[69]-JVS[804]
          *XX[70])/(JVS[837]);
  XX[72] = (X[72]-JVS[39]*XX[3]-JVS[47]*XX[5]-JVS[71]*XX[13]-JVS[269]
          *XX[45]-JVS[303]*XX[47]-JVS[361]*XX[54]-JVS[397]*XX[55]
          -JVS[495]*XX[60]-JVS[515]*XX[61]-JVS[563]*XX[62]-JVS[593]
          *XX[63]-JVS[613]*XX[64]-JVS[642]*XX[65]-JVS[659]*XX[66]
          -JVS[699]*XX[67]-JVS[724]*XX[68]-JVS[766]*XX[69]-JVS[805]
          *XX[70]-JVS[838]*XX[71])/(JVS[863]);
  XX[73] = (X[73]-JVS[2]*XX[0]-JVS[16]*XX[1]-JVS[56]*XX[8]-JVS[60]
          *XX[10]-JVS[65]*XX[11]-JVS[80]*XX[16]-JVS[86]*XX[18]-JVS[88]
          *XX[19]-JVS[90]*XX[20]-JVS[94]*XX[21]-JVS[96]*XX[22]-JVS[98]
          *XX[23]-JVS[102]*XX[24]-JVS[106]*XX[25]-JVS[120]*XX[28]
          -JVS[122]*XX[29]-JVS[124]*XX[30]-JVS[128]*XX[31]-JVS[132]
          *XX[32]-JVS[137]*XX[33]-JVS[142]*XX[34]-JVS[153]*XX[36]
          -JVS[160]*XX[37]-JVS[166]*XX[38]-JVS[189]*XX[39]-JVS[201]
          *XX[40]-JVS[215]*XX[41]-JVS[236]*XX[42]-JVS[241]*XX[43]
          -JVS[258]*XX[44]-JVS[270]*XX[45]-JVS[275]*XX[46]-JVS[304]
          *XX[47]-JVS[309]*XX[48]-JVS[316]*XX[49]-JVS[321]*XX[50]
          -JVS[328]*XX[51]-JVS[333]*XX[52]-JVS[340]*XX[53]-JVS[362]
          *XX[54]-JVS[398]*XX[55]-JVS[411]*XX[56]-JVS[425]*XX[57]
          -JVS[453]*XX[58]-JVS[473]*XX[59]-JVS[496]*XX[60]-JVS[516]
          *XX[61]-JVS[564]*XX[62]-JVS[594]*XX[63]-JVS[614]*XX[64]
          -JVS[643]*XX[65]-JVS[660]*XX[66]-JVS[700]*XX[67]-JVS[725]
          *XX[68]-JVS[767]*XX[69]-JVS[806]*XX[70]-JVS[839]*XX[71]
          -JVS[864]*XX[72])/(JVS[919]);
  XX[73] = XX[73];
  XX[72] = XX[72]-JVS[918]*XX[73];
  XX[71] = XX[71]-JVS[862]*XX[72]-JVS[917]*XX[73];
  XX[70] = XX[70]-JVS[836]*XX[71]-JVS[861]*XX[72]-JVS[916]*XX[73];
  XX[69] = XX[69]-JVS[802]*XX[70]-JVS[835]*XX[71]-JVS[860]*XX[72]
          -JVS[915]*XX[73];
  XX[68] = XX[68]-JVS[762]*XX[69]-JVS[801]*XX[70]-JVS[834]*XX[71]
          -JVS[859]*XX[72]-JVS[914]*XX[73];
  XX[67] = XX[67]-JVS[719]*XX[68]-JVS[761]*XX[69]-JVS[800]*XX[70]
          -JVS[833]*XX[71]-JVS[858]*XX[72]-JVS[913]*XX[73];
  XX[66] = XX[66]-JVS[693]*XX[67]-JVS[718]*XX[68]-JVS[760]*XX[69]
          -JVS[799]*XX[70]-JVS[832]*XX[71]-JVS[857]*XX[72]-JVS[912]
          *XX[73];
  XX[65] = XX[65]-JVS[652]*XX[66]-JVS[692]*XX[67]-JVS[717]*XX[68]
          -JVS[759]*XX[69]-JVS[798]*XX[70]-JVS[831]*XX[71]-JVS[856]
          *XX[72]-JVS[911]*XX[73];
  XX[64] = XX[64]-JVS[634]*XX[65]-JVS[651]*XX[66]-JVS[691]*XX[67]
          -JVS[716]*XX[68]-JVS[758]*XX[69]-JVS[797]*XX[70]-JVS[830]
          *XX[71]-JVS[855]*XX[72]-JVS[910]*XX[73];
  XX[63] = XX[63]-JVS[604]*XX[64]-JVS[633]*XX[65]-JVS[650]*XX[66]
          -JVS[690]*XX[67]-JVS[715]*XX[68]-JVS[757]*XX[69]-JVS[796]
          *XX[70]-JVS[829]*XX[71]-JVS[854]*XX[72]-JVS[909]*XX[73];
  XX[62] = XX[62]-JVS[583]*XX[63]-JVS[603]*XX[64]-JVS[632]*XX[65]
          -JVS[649]*XX[66]-JVS[689]*XX[67]-JVS[714]*XX[68]-JVS[756]
          *XX[69]-JVS[795]*XX[70]-JVS[828]*XX[71]-JVS[853]*XX[72]
          -JVS[908]*XX[73];
  XX[61] = XX[61]-JVS[552]*XX[62]-JVS[582]*XX[63]-JVS[602]*XX[64]
          -JVS[631]*XX[65]-JVS[648]*XX[66]-JVS[688]*XX[67]-JVS[713]
          *XX[68]-JVS[755]*XX[69]-JVS[794]*XX[70]-JVS[827]*XX[71]
          -JVS[852]*XX[72]-JVS[907]*XX[73];
  XX[60] = XX[60]-JVS[551]*XX[62]-JVS[581]*XX[63]-JVS[630]*XX[65]
          -JVS[687]*XX[67]-JVS[712]*XX[68]-JVS[754]*XX[69]-JVS[793]
          *XX[70]-JVS[826]*XX[71]-JVS[851]*XX[72]-JVS[906]*XX[73];
  XX[59] = XX[59]-JVS[550]*XX[62]-JVS[580]*XX[63]-JVS[629]*XX[65]
          -JVS[686]*XX[67]-JVS[711]*XX[68]-JVS[753]*XX[69]-JVS[792]
          *XX[70]-JVS[825]*XX[71]-JVS[850]*XX[72]-JVS[905]*XX[73];
  XX[58] = XX[58]-JVS[549]*XX[62]-JVS[579]*XX[63]-JVS[628]*XX[65]
          -JVS[685]*XX[67]-JVS[752]*XX[69]-JVS[791]*XX[70]-JVS[824]
          *XX[71]-JVS[849]*XX[72]-JVS[904]*XX[73];
  XX[57] = XX[57]-JVS[442]*XX[58]-JVS[463]*XX[59]-JVS[484]*XX[60]
          -JVS[506]*XX[61]-JVS[548]*XX[62]-JVS[578]*XX[63]-JVS[601]
          *XX[64]-JVS[627]*XX[65]-JVS[647]*XX[66]-JVS[684]*XX[67]
          -JVS[710]*XX[68]-JVS[751]*XX[69]-JVS[790]*XX[70]-JVS[823]
          *XX[71]-JVS[848]*XX[72]-JVS[903]*XX[73];
  XX[56] = XX[56]-JVS[441]*XX[58]-JVS[462]*XX[59]-JVS[483]*XX[60]
          -JVS[547]*XX[62]-JVS[577]*XX[63]-JVS[626]*XX[65]-JVS[683]
          *XX[67]-JVS[709]*XX[68]-JVS[750]*XX[69]-JVS[789]*XX[70]
          -JVS[822]*XX[71]-JVS[902]*XX[73];
  XX[55] = XX[55]-JVS[546]*XX[62]-JVS[708]*XX[68]-JVS[749]*XX[69]
          -JVS[788]*XX[70]-JVS[901]*XX[73];
  XX[54] = XX[54]-JVS[545]*XX[62]-JVS[625]*XX[65]-JVS[748]*XX[69]
          -JVS[787]*XX[70]-JVS[821]*XX[71]-JVS[900]*XX[73];
  XX[53] = XX[53]-JVS[380]*XX[55]-JVS[419]*XX[57]-JVS[440]*XX[58]
          -JVS[461]*XX[59]-JVS[482]*XX[60]-JVS[505]*XX[61]-JVS[544]
          *XX[62]-JVS[576]*XX[63]-JVS[600]*XX[64]-JVS[624]*XX[65]
          -JVS[682]*XX[67]-JVS[707]*XX[68]-JVS[747]*XX[69]-JVS[786]
          *XX[70]-JVS[820]*XX[71]-JVS[847]*XX[72]-JVS[899]*XX[73];
  XX[52] = XX[52]-JVS[335]*XX[53]-JVS[348]*XX[54]-JVS[379]*XX[55]
          -JVS[403]*XX[56]-JVS[418]*XX[57]-JVS[439]*XX[58]-JVS[460]
          *XX[59]-JVS[481]*XX[60]-JVS[504]*XX[61]-JVS[543]*XX[62]
          -JVS[575]*XX[63]-JVS[599]*XX[64]-JVS[623]*XX[65]-JVS[646]
          *XX[66]-JVS[681]*XX[67]-JVS[706]*XX[68]-JVS[746]*XX[69]
          -JVS[785]*XX[70]-JVS[819]*XX[71]-JVS[846]*XX[72]-JVS[898]
          *XX[73];
  XX[51] = XX[51]-JVS[347]*XX[54]-JVS[378]*XX[55]-JVS[402]*XX[56]
          -JVS[438]*XX[58]-JVS[459]*XX[59]-JVS[480]*XX[60]-JVS[503]
          *XX[61]-JVS[542]*XX[62]-JVS[574]*XX[63]-JVS[598]*XX[64]
          -JVS[680]*XX[67]-JVS[745]*XX[69]-JVS[784]*XX[70]-JVS[818]
          *XX[71]-JVS[845]*XX[72]-JVS[897]*XX[73];
  XX[50] = XX[50]-JVS[346]*XX[54]-JVS[377]*XX[55]-JVS[401]*XX[56]
          -JVS[417]*XX[57]-JVS[437]*XX[58]-JVS[458]*XX[59]-JVS[479]
          *XX[60]-JVS[502]*XX[61]-JVS[541]*XX[62]-JVS[573]*XX[63]
          -JVS[622]*XX[65]-JVS[679]*XX[67]-JVS[705]*XX[68]-JVS[744]
          *XX[69]-JVS[783]*XX[70]-JVS[817]*XX[71]-JVS[896]*XX[73];
  XX[49] = XX[49]-JVS[376]*XX[55]-JVS[416]*XX[57]-JVS[436]*XX[58]
          -JVS[457]*XX[59]-JVS[501]*XX[61]-JVS[540]*XX[62]-JVS[597]
          *XX[64]-JVS[678]*XX[67]-JVS[743]*XX[69]-JVS[782]*XX[70]
          -JVS[816]*XX[71]-JVS[844]*XX[72]-JVS[895]*XX[73];
  XX[48] = XX[48]-JVS[375]*XX[55]-JVS[400]*XX[56]-JVS[415]*XX[57]
          -JVS[435]*XX[58]-JVS[478]*XX[60]-JVS[500]*XX[61]-JVS[539]
          *XX[62]-JVS[572]*XX[63]-JVS[621]*XX[65]-JVS[677]*XX[67]
          -JVS[704]*XX[68]-JVS[742]*XX[69]-JVS[781]*XX[70]-JVS[815]
          *XX[71]-JVS[843]*XX[72]-JVS[894]*XX[73];
  XX[47] = XX[47]-JVS[703]*XX[68]-JVS[741]*XX[69]-JVS[780]*XX[70];
  XX[46] = XX[46]-JVS[282]*XX[47]-JVS[310]*XX[49]-JVS[322]*XX[51]
          -JVS[334]*XX[53]-JVS[374]*XX[55]-JVS[414]*XX[57]-JVS[477]
          *XX[60]-JVS[499]*XX[61]-JVS[538]*XX[62]-JVS[571]*XX[63]
          -JVS[596]*XX[64]-JVS[620]*XX[65]-JVS[676]*XX[67]-JVS[740]
          *XX[69]-JVS[779]*XX[70]-JVS[893]*XX[73];
  XX[45] = XX[45]-JVS[373]*XX[55]-JVS[537]*XX[62]-JVS[675]*XX[67]
          -JVS[739]*XX[69]-JVS[778]*XX[70]-JVS[842]*XX[72]-JVS[892]
          *XX[73];
  XX[44] = XX[44]-JVS[372]*XX[55]-JVS[536]*XX[62]-JVS[738]*XX[69]
          -JVS[777]*XX[70]-JVS[841]*XX[72]-JVS[891]*XX[73];
  XX[43] = XX[43]-JVS[249]*XX[44]-JVS[345]*XX[54]-JVS[371]*XX[55]
          -JVS[413]*XX[57]-JVS[434]*XX[58]-JVS[498]*XX[61]-JVS[535]
          *XX[62]-JVS[619]*XX[65]-JVS[674]*XX[67]-JVS[776]*XX[70]
          -JVS[890]*XX[73];
  XX[42] = XX[42]-JVS[737]*XX[69]-JVS[775]*XX[70]-JVS[889]*XX[73];
  XX[41] = XX[41]-JVS[281]*XX[47]-JVS[370]*XX[55]-JVS[618]*XX[65]
          -JVS[814]*XX[71]-JVS[888]*XX[73];
  XX[40] = XX[40]-JVS[221]*XX[42]-JVS[534]*XX[62]-JVS[774]*XX[70]
          -JVS[813]*XX[71]-JVS[887]*XX[73];
  XX[39] = XX[39]-JVS[533]*XX[62]-JVS[886]*XX[73];
  XX[38] = XX[38]-JVS[220]*XX[42]-JVS[248]*XX[44]-JVS[260]*XX[45]
          -JVS[673]*XX[67]-JVS[773]*XX[70]-JVS[885]*XX[73];
  XX[37] = XX[37]-JVS[219]*XX[42]-JVS[645]*XX[66]-JVS[772]*XX[70]
          -JVS[884]*XX[73];
  XX[36] = XX[36]-JVS[433]*XX[58]-JVS[532]*XX[62]-JVS[672]*XX[67]
          -JVS[883]*XX[73];
  XX[35] = XX[35]-JVS[218]*XX[42]-JVS[531]*XX[62]-JVS[736]*XX[69]
          -JVS[771]*XX[70];
  XX[34] = XX[34]-JVS[171]*XX[39]-JVS[247]*XX[44]-JVS[432]*XX[58]
          -JVS[497]*XX[61]-JVS[530]*XX[62]-JVS[671]*XX[67]-JVS[882]
          *XX[73];
  XX[33] = XX[33]-JVS[194]*XX[40]-JVS[217]*XX[42]-JVS[259]*XX[45]
          -JVS[670]*XX[67]-JVS[770]*XX[70]-JVS[881]*XX[73];
  XX[32] = XX[32]-JVS[170]*XX[39]-JVS[193]*XX[40]-JVS[246]*XX[44]
          -JVS[280]*XX[47]-JVS[431]*XX[58]-JVS[529]*XX[62]-JVS[669]
          *XX[67]-JVS[812]*XX[71]-JVS[880]*XX[73];
  XX[31] = XX[31]-JVS[169]*XX[39]-JVS[192]*XX[40]-JVS[245]*XX[44]
          -JVS[279]*XX[47]-JVS[430]*XX[58]-JVS[528]*XX[62]-JVS[668]
          *XX[67]-JVS[811]*XX[71]-JVS[879]*XX[73];
  XX[30] = XX[30]-JVS[126]*XX[31]-JVS[130]*XX[32]-JVS[134]*XX[33]
          -JVS[139]*XX[34]-JVS[155]*XX[37]-JVS[161]*XX[38]-JVS[191]
          *XX[40]-JVS[244]*XX[44]-JVS[476]*XX[60]-JVS[527]*XX[62]
          -JVS[570]*XX[63]-JVS[667]*XX[67]-JVS[878]*XX[73];
  XX[29] = XX[29]-JVS[168]*XX[39]-JVS[206]*XX[41]-JVS[278]*XX[47]
          -JVS[344]*XX[54]-JVS[369]*XX[55]-JVS[429]*XX[58]-JVS[456]
          *XX[59]-JVS[475]*XX[60]-JVS[569]*XX[63]-JVS[617]*XX[65]
          -JVS[666]*XX[67]-JVS[810]*XX[71]-JVS[877]*XX[73];
  XX[28] = XX[28]-JVS[368]*XX[55]-JVS[526]*XX[62]-JVS[876]*XX[73];
  XX[27] = XX[27]-JVS[143]*XX[35]-JVS[525]*XX[62]-JVS[735]*XX[69];
  XX[26] = XX[26]-JVS[367]*XX[55]-JVS[524]*XX[62]-JVS[702]*XX[68]
          -JVS[734]*XX[69];
  XX[25] = XX[25]-JVS[366]*XX[55]-JVS[523]*XX[62]-JVS[616]*XX[65]
          -JVS[875]*XX[73];
  XX[24] = XX[24]-JVS[522]*XX[62]-JVS[733]*XX[69]-JVS[769]*XX[70]
          -JVS[874]*XX[73];
  XX[23] = XX[23]-JVS[125]*XX[31]-JVS[129]*XX[32]-JVS[133]*XX[33]
          -JVS[138]*XX[34]-JVS[154]*XX[37]-JVS[190]*XX[40]-JVS[243]
          *XX[44]-JVS[521]*XX[62]-JVS[568]*XX[63]-JVS[665]*XX[67]
          -JVS[809]*XX[71]-JVS[873]*XX[73];
  XX[22] = XX[22]-JVS[205]*XX[41]-JVS[277]*XX[47]-JVS[343]*XX[54]
          -JVS[365]*XX[55]-JVS[428]*XX[58]-JVS[455]*XX[59]-JVS[474]
          *XX[60]-JVS[567]*XX[63]-JVS[664]*XX[67]-JVS[872]*XX[73];
  XX[21] = XX[21]-JVS[204]*XX[41]-JVS[399]*XX[56]-JVS[615]*XX[65]
          -JVS[732]*XX[69];
  XX[20] = XX[20]-JVS[91]*XX[21]-JVS[203]*XX[41]-JVS[276]*XX[47]
          -JVS[342]*XX[54]-JVS[364]*XX[55]-JVS[427]*XX[58]-JVS[454]
          *XX[59]-JVS[566]*XX[63]-JVS[663]*XX[67]-JVS[871]*XX[73];
  XX[19] = XX[19]-JVS[167]*XX[39]-JVS[202]*XX[41]-JVS[242]*XX[44]
          -JVS[363]*XX[55]-JVS[426]*XX[58]-JVS[520]*XX[62]-JVS[565]
          *XX[63]-JVS[662]*XX[67]-JVS[870]*XX[73];
  XX[18] = XX[18]-JVS[519]*XX[62]-JVS[701]*XX[68]-JVS[731]*XX[69]
          -JVS[869]*XX[73];
  XX[17] = XX[17]-JVS[216]*XX[42]-JVS[730]*XX[69]-JVS[768]*XX[70];
  XX[16] = XX[16]-JVS[518]*XX[62]-JVS[868]*XX[73];
  XX[15] = XX[15]-JVS[595]*XX[64]-JVS[729]*XX[69];
  XX[14] = XX[14]-JVS[644]*XX[66]-JVS[728]*XX[69];
  XX[13] = XX[13]-JVS[727]*XX[69]-JVS[840]*XX[72];
  XX[12] = XX[12]-JVS[726]*XX[69]-JVS[808]*XX[71];
  XX[11] = XX[11]-JVS[807]*XX[71];
  XX[10] = XX[10]-JVS[341]*XX[54]-JVS[661]*XX[67]-JVS[867]*XX[73];
  XX[9] = XX[9]-JVS[412]*XX[57]-JVS[866]*XX[73];
  XX[8] = XX[8]-JVS[517]*XX[62]-JVS[865]*XX[73];
  XX[7] = XX[7];
  XX[6] = XX[6];
  XX[5] = XX[5];
  XX[4] = XX[4];
  XX[3] = XX[3];
  XX[2] = XX[2];
  XX[1] = XX[1];
  XX[0] = XX[0];
}

/* End of KppSolveTR function                                       */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* BLAS_UTIL - BLAS-LIKE utility functions                          */
/*   Arguments :                                                    */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/*--------------------------------------------------------------
 
  BLAS/LAPACK-like subroutines used by the integration algorithms
  It is recommended to replace them by calls to the optimized
       BLAS/LAPACK library for your machine
 
   (C) Adrian Sandu, Aug. 2004
 
--------------------------------------------------------------*/

#define ZERO  (double)0.0
#define ONE   (double)1.0
#define HALF  (double)0.5
#define TWO   (double)2.0
#define MOD(A,B) (int)((A)%(B))

/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
void WCOPY(int N, double X[], int incX, double Y[], int incY)
/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    copies a vector, x, to a vector, y:  y <- x
    only for incX=incY=1
    after BLAS
    replace this by the function from the optimized BLAS implementation:
        CALL  SCOPY(N,X,1,Y,1)   or   CALL  DCOPY(N,X,1,Y,1)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
{
      int i, M;
      if (N <= 0) return;

      M = MOD(N,8);
      if( M != 0 ) {
        for ( i = 0; i < M; i++ )
          Y[i] = X[i];
        if( N < 8 ) return;
      } /* end if */	
      for ( i = M; i<N; i+=8 ) {
        Y[i] = X[i];
        Y[i + 1] = X[i + 1];
        Y[i + 2] = X[i + 2];
        Y[i + 3] = X[i + 3];
        Y[i + 4] = X[i + 4];
        Y[i + 5] = X[i + 5];
        Y[i + 6] = X[i + 6];
        Y[i + 7] = X[i + 7];
      } /* end for */

} /* end function WCOPY */


/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
void WAXPY(int N, double Alpha, 
         double X[], int incX, 
	 double Y[], int incY )
/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    constant times a vector plus a vector: y <- y + Alpha*x
    only for incX=incY=1
    after BLAS
    replace this by the function from the optimized BLAS implementation:
        CALL SAXPY(N,Alpha,X,1,Y,1) or  CALL DAXPY(N,Alpha,X,1,Y,1)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
{
      int i, M;

      if (Alpha == ZERO) return;
      if (N  <=  0) return;

      M = MOD(N,4);
      if( M != 0 ) {
        for ( i = 0; i < M; i++ )
          Y[i] = Y[i] + Alpha*X[i];
        if ( N < 4 ) return;
      } /* end if */
      
      for ( i = M; i < N; i += 4 ) {
        Y[i] = Y[i] + Alpha*X[i];
        Y[i + 1] = Y[i + 1] + Alpha*X[i + 1];
        Y[i + 2] = Y[i + 2] + Alpha*X[i + 2];
        Y[i + 3] = Y[i + 3] + Alpha*X[i + 3];
      } /* end for */

} /* end function  WAXPY */



/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
void WSCAL(int N, double Alpha, double X[], int incX)
/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    constant times a vector: x(1:N) <- Alpha*x(1:N) 
    only for incX=incY=1
    after BLAS
    replace this by the function from the optimized BLAS implementation:
        CALL SSCAL(N,Alpha,X,1) or  CALL DSCAL(N,Alpha,X,1)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
{
      int i, M;
      
      if (Alpha == ONE) return;
      if (N  <=  0) return;

      M = MOD(N,5);
      if( M  !=  0 ) {
        if (Alpha == (-ONE))
          for ( i = 0; i < M; i++ )  X[i] = -X[i];
        else {
	  if (Alpha == ZERO)
            for ( i = 0; i < M; i++ ) X[i] = ZERO;
          else
            for ( i = 0; i < M; i++ ) X[i] = Alpha*X[i];
        } /* end else */
        if( N < 5 ) return;
      } /* end if */
      
      if (Alpha == (-ONE))
        for ( i = M; i<N; i+=5 ) {
          X[i]     = -X[i];
          X[i + 1] = -X[i + 1];
          X[i + 2] = -X[i + 2];
          X[i + 3] = -X[i + 3];
          X[i + 4] = -X[i + 4];
        } /* end for */
      else {
        if (Alpha == ZERO)
          for ( i = M; i < N; i += 5 ) {
            X[i]     = ZERO;
            X[i + 1] = ZERO;
            X[i + 2] = ZERO;
            X[i + 3] = ZERO;
            X[i + 4] = ZERO;
          } /* end for */
        else
          for ( i = M; i < N; i += 5 ) {
            X[i]     = Alpha*X[i];
            X[i + 1] = Alpha*X[i + 1];
            X[i + 2] = Alpha*X[i + 2];
            X[i + 3] = Alpha*X[i + 3];
            X[i + 4] = Alpha*X[i + 4];
           } /* end for */
      }  /* else  */
      
} /* end function WSCAL */
   
     
/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
double WLAMCH_ADD( double  A, double  B )
{
      return (A + B);
} /* end function  WLAMCH_ADD */

/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
double WLAMCH( char C )
/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    returns epsilon machine
    after LAPACK
    replace this by the function from the optimized LAPACK implementation:
         CALL SLAMCH('E') or CALL DLAMCH('E')
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
{
      int i;
      double Suma;
      static double Eps;
      static char First = 1;
      
      if (First) {
        First = 0;
        Eps = pow(HALF,16);
        for ( i = 17; i <= 80; i++ ) {
          Eps = Eps*HALF;
	  Suma = WLAMCH_ADD(ONE,Eps);
	  if (Suma <= ONE) break;
        } /* end for */
        if (i==80) {
	   printf("\nERROR IN WLAMCH. Very small EPS = %g\n",Eps);
           return (double)2.2e-16;
	}
        Eps *= TWO; i--;      
      } /* end if First */

      return Eps;

} /* end function WLAMCH */


/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 	copies zeros into the vector y:  y <- 0 after BLAS
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
void Set2Zero(int N, double Y[])
{
   int i,M;
	
   if (N <= 0) return;

   M = MOD(N,8);
   if  (M != 0)
   {
	for (i = 0; i < M; i++)
	{
	   Y[i] = ZERO;
	}
	if (N < 8) 
	   return;
   } /* end if */
   for (i = M; i < N; i += 8)
   {
   	Y[i] = ZERO;
	Y[i + 1] = ZERO;
        Y[i + 2] = ZERO;
	Y[i + 3] = ZERO;
	Y[i + 4] = ZERO;
	Y[i + 5] = ZERO;
	Y[i + 6] = ZERO;
	Y[i + 7] = ZERO;
   } /* end for */
} /* end function Set2Zero */


/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	adds two vectors: z <- x + y     BLAS - like
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
void WADD(int N, double X[], double Y[], double Z[])
{
	int i, M;

	if ( N <= 0 ) return;
	
	M = MOD(N,5);
	if ( M != 0 )
	{
	   for(i = 0; i < M; i++)
	   {
		Z[i] = X[i] + Y[i];
	   }
	   if ( N < 5 ) return;
	} /* end if */
	for (i = M; i < N; i += 5)
	{
	   Z[i] = X[i] + Y[i];
	   Z[i + 1] = X[i + 1] + Y[i + 1];
	   Z[i + 2] = X[i + 2] + Y[i + 2];
	   Z[i + 3] = X[i + 3] + Y[i + 3];
	   Z[i + 4] = X[i + 4] + Y[i + 4];
	} /* end for */
} /* end function WADD */
/* End of BLAS_UTIL function                                        */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#endif
