/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Parameter Header File                                            */
/*                                                                  */
/* Generated by KPP-2.2 symbolic chemistry Kinetics PreProcessor    */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : saprc99_Parameters.h                      */
/* Time                 : Wed Jun 11 10:09:48 2008                  */
/* Working directory    : /Users/jlinford/workspace/saprc99         */
/* Equation file        : saprc99.kpp                               */
/* Output root filename : saprc99                                   */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#ifndef __SAPRC99_PARAMETERS_H__
#define __SAPRC99_PARAMETERS_H__

#include "params.h"

#define CFACTOR              2.4476e+13  /* Species conversion factor */

#if DO_CHEMISTRY == 1

#define NSPEC                79          /* Number of chemical species */
#define NVAR                 74          /* Number of Variable species */
#define NVARACT              66          /* Number of Active species */
#define NFIX                 5           /* Number of Fixed species */
#define NREACT               211         /* Number of reactions */
#define NVARST               0           /* Starting of variables in conc. vect. */
#define NFIXST               74          /* Starting of fixed in conc. vect. */
#define NONZERO              839         /* Number of nonzero entries in Jacobian */
#define LU_NONZERO           920         /* Number of nonzero entries in LU factoriz. of Jacobian */
#define CNVAR                75          /* (NVAR+1) Number of elements in compressed row format */
#define NLOOKAT              79          /* Number of species to look at */
#define NMONITOR             4           /* Number of species to monitor */

/* Index declaration for variable species in C and VAR              */
/*   VAR(ind_spc) = C(ind_spc)                                      */

#define ind_H2SO4            0          
#define ind_HCOOH            1          
#define ind_CCO_OH           2          
#define ind_RCO_OH           3          
#define ind_CCO_OOH          4          
#define ind_RCO_OOH          5          
#define ind_XN               6          
#define ind_XC               7          
#define ind_SO2              8          
#define ind_O1D              9          
#define ind_ALK1             10         
#define ind_BACL             11         
#define ind_PAN              12         
#define ind_PAN2             13         
#define ind_PBZN             14         
#define ind_MA_PAN           15         
#define ind_H2O2             16         
#define ind_N2O5             17         
#define ind_HONO             18         
#define ind_ALK2             19         
#define ind_ALK3             20         
#define ind_TBU_O            21         
#define ind_ALK5             22         
#define ind_ARO2             23         
#define ind_HNO4             24         
#define ind_COOH             25         
#define ind_HOCOO            26         
#define ind_BZNO2_O          27         
#define ind_MEOH             28         
#define ind_ALK4             29         
#define ind_ARO1             30         
#define ind_DCB2             31         
#define ind_DCB3             32         
#define ind_CRES             33         
#define ind_DCB1             34         
#define ind_NPHE             35         
#define ind_ROOH             36         
#define ind_BALD             37         
#define ind_PHEN             38         
#define ind_CO               39         
#define ind_MGLY             40         
#define ind_ACET             41         
#define ind_HNO3             42         
#define ind_ETHENE           43         
#define ind_GLY              44         
#define ind_BZ_O             45         
#define ind_ISOPRENE         46         
#define ind_R2O2             47         
#define ind_TERP             48         
#define ind_METHACRO         49         
#define ind_OLE1             50         
#define ind_ISOPROD          51         
#define ind_OLE2             52         
#define ind_MVK              53         
#define ind_CCHO             54         
#define ind_HCHO             55         
#define ind_RNO3             56         
#define ind_O3P              57         
#define ind_RCHO             58         
#define ind_MEK              59         
#define ind_PROD2            60         
#define ind_O3               61         
#define ind_HO2              62         
#define ind_RO2_N            63         
#define ind_MA_RCO3          64         
#define ind_C_O2             65         
#define ind_BZCO_O2          66         
#define ind_RO2_R            67         
#define ind_NO               68         
#define ind_NO2              69         
#define ind_NO3              70         
#define ind_CCO_O2           71         
#define ind_RCO_O2           72         
#define ind_OH               73         

/* Index declaration for fixed species in C                         */
/*   C(ind_spc)                                                     */

#define ind_AIR              74         
#define ind_O2               75         
#define ind_H2O              76         
#define ind_H2               77         
#define ind_CH4              78         

/* Index declaration for fixed species in FIX                       */
/*    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)                 */

#define indf_AIR             0          
#define indf_O2              1          
#define indf_H2O             2          
#define indf_H2              3          
#define indf_CH4             4

#else

#define NSPEC                1           /* Number of chemical species */
#define NVAR                 1           /* Number of Variable species */
#define NVARACT              1           /* Number of Active species */
#define NFIX                 0           /* Number of Fixed species */
#define NREACT               0           /* Number of reactions */
#define NVARST               0           /* Starting of variables in conc. vect. */
#define NFIXST               0           /* Starting of fixed in conc. vect. */
#define NONZERO              0           /* Number of nonzero entries in Jacobian */
#define LU_NONZERO           0           /* Number of nonzero entries in LU factoriz. of Jacobian */
#define CNVAR                0           /* (NVAR+1) Number of elements in compressed row format */
#define NLOOKAT              1           /* Number of species to look at */
#define NMONITOR             1           /* Number of species to monitor */

#define ind_O3               0

#endif

#endif
