prefix=/usr/local
exec_prefix=${prefix}
bindir=${exec_prefix}/bin
libdir=${exec_prefix}/lib
includedir=${prefix}/include
ARCH=PPC
SYS=LINUX
CC=gcc
CFLAGS=-O4 -ffast-math  -Wall -I. -DHAVE_MALLOC_H -DARCH_PPC -DSYS_LINUX -DWORDS_BIGENDIAN -s -fomit-frame-pointer
ALTIVECFLAGS= -maltivec -mabi=altivec
LDFLAGS= -lm -s
AS=
ASFLAGS=
GTK=no
EXE=
VIS=no
HAVE_GETOPT_LONG=1
DEVNULL=/dev/null
ECHON=echo -n
CONFIGURE_ARGS= '--disable-pthread'
